db.blueprints.insertMany([
  {
    name: "Squire Sword",
    type: "Sword",
    tier: 1,
    unlockPrerequisite: "Blacksmith",
  },
  { name: "Arming Sword", type: "Sword", tier: 2 },
  { name: "Gladius", type: "Sword", tier: 3 },
  {
    name: "Arboreal Blade",
    type: "Sword",
    tier: 3,
    unlockPrerequisite: "Frozen Chest",
  },
  {
    name: "Zweihander",
    type: "Sword",
    tier: 3,
    unlockPrerequisite: "Oktoberfest Pack",
  },
  { name: "Cutlass", type: "Sword", tier: 4 },
  { name: "Espada", type: "Sword", tier: 5 },
  {
    name: "Hero's Sword",
    type: "Sword",
    tier: 5,
    unlockPrerequisite: "Hero Pack",
  },
  {
    name: "Chocolicious Blade",
    type: "Sword",
    tier: 5,
    unlockPrerequisite: "Super Sweet Mega Pack",
  },
  { name: "Katana", type: "Sword", tier: 6 },
  {
    name: "Serrated Cinquedea",
    type: "Sword",
    tier: 6,
    unlockPrerequisite: "Autumn Mega Pack",
  },
  { name: "Regal Blade", type: "Sword", tier: 7 },
  {
    name: "Chronos Runeblade",
    type: "Sword",
    tier: 7,
    unlockPrerequisite: "Chronos Ruins Mega Pack",
  },
  { name: "Celesteel Blade", type: "Sword", tier: 8 },
  {
    name: "Damocles",
    type: "Sword",
    tier: 8,
    unlockPrerequisite: "Timeworn Chest",
  },
  {
    name: "Luxurious Macuahuitl",
    type: "Sword",
    tier: 8,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Mythril Edge", type: "Sword", tier: 9 },
  {
    name: "Seafarer Blade",
    type: "Sword",
    tier: 9,
    unlockPrerequisite: "Champion Clash Superior Pack",
  },
  {
    name: "Gentleman Blade",
    type: "Sword",
    tier: 9,
    unlockPrerequisite: "Victorian Mega Pack",
  },
  { name: "Oversized Cleaver", type: "Sword", tier: 10 },
  {
    name: "Caladbolg",
    type: "Sword",
    tier: 10,
    unlockPrerequisite: "Sunken Chest",
  },
  {
    name: "Dragon Dao",
    type: "Sword",
    tier: 10,
    unlockPrerequisite: "Dragon Siblings Superior Offer",
  },
  {
    name: "Tiger Blade",
    type: "Sword",
    tier: 10,
    unlockPrerequisite: "Content Pass: Year of the Tiger",
  },
  { name: "Vorpal Sword", type: "Sword", tier: 11 },
  {
    name: "Elegant Rapier",
    type: "Sword",
    tier: 11,
    unlockPrerequisite: "Victorian Spring Mega Pack",
  },
  {
    name: "Tsukuyomi",
    type: "Sword",
    tier: 11,
    unlockPrerequisite: "Moon Festival Superior Pack",
  },
  { name: "Excalibur", type: "Sword", tier: 12 },
  {
    name: "Titan Sword",
    type: "Sword",
    tier: 12,
    unlockPrerequisite: "Shop Titans Superior Pack",
  },
  {
    name: "Opulent Brand",
    type: "Sword",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Épée d'Artagnan",
    type: "Sword",
    tier: 12,
    unlockPrerequisite: "Musketeer Mega Pack",
  },
  {
    name: "Thorn of Scorn",
    type: "Sword",
    tier: 12,
    unlockPrerequisite: "Pumpkin Superior Pack",
  },
  { name: "Djinn Pyre", type: "Sword", tier: 13 },
  {
    name: "Plasma Saber",
    type: "Sword",
    tier: 13,
    unlockPrerequisite: "Content Pass: Spacefarer",
  },
  { name: "Wood Axe", type: "Axe", tier: 1 },
  { name: "Hatchet", type: "Axe", tier: 2 },
  { name: "Iron Chopper", type: "Axe", tier: 3 },
  {
    name: "Explorer's Axe",
    type: "Axe",
    tier: 3,
    unlockPrerequisite: "Explorer Pack",
  },
  { name: "Bardiche", type: "Axe", tier: 4 },
  {
    name: "Molten Voulge",
    type: "Axe",
    tier: 4,
    unlockPrerequisite: "Frozen Chest",
  },
  { name: "Dismantler's Pickaxe", type: "Axe", tier: 4 },
  { name: "Tomahawk", type: "Axe", tier: 5 },
  {
    name: "Companion Axe",
    type: "Axe",
    tier: 5,
    unlockPrerequisite: "Expert Pack",
  },
  {
    name: "Cold Iron Axe",
    type: "Axe",
    tier: 5,
    unlockPrerequisite: "Snow Day Mega Pack",
  },
  { name: "Battleaxe", type: "Axe", tier: 6 },
  {
    name: "Raptor Reaper",
    type: "Axe",
    tier: 6,
    unlockPrerequisite: "Pollux Mega Pack",
  },
  { name: "Dwarven Greataxe", type: "Axe", tier: 7 },
  {
    name: "Stonesplitter",
    type: "Axe",
    tier: 7,
    unlockPrerequisite: "Ancient Chest",
  },
  { name: "Raider Axe", type: "Axe", tier: 8 },
  {
    name: "Qian Chopper",
    type: "Axe",
    tier: 8,
    unlockPrerequisite: "Content Pass: Year of the Rabbit",
  },
  { name: "Executioner", type: "Axe", tier: 9 },
  {
    name: "Purgatory",
    type: "Axe",
    tier: 9,
    unlockPrerequisite: "Forsaken Chest",
  },
  {
    name: "Axe of The Fifth",
    type: "Axe",
    tier: 9,
    unlockPrerequisite: "Cinco De Mayo Mega Pack",
  },
  { name: "Eclipsis", type: "Axe", tier: 10 },
  {
    name: "Terra Tyrannis",
    type: "Axe",
    tier: 10,
    unlockPrerequisite: "Sunken Chest",
  },
  {
    name: "Opulent Grandaxe",
    type: "Axe",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Kodiak Kleaver",
    type: "Axe",
    tier: 10,
    unlockPrerequisite: "Wild Love Mega Pack",
  },
  { name: "Manticore Slayer", type: "Axe", tier: 11 },
  {
    name: "Beeswaxe",
    type: "Axe",
    tier: 11,
    unlockPrerequisite: "Bee's Knees Mega Pack",
  },
  {
    name: "Shroom Doom",
    type: "Axe",
    tier: 11,
    unlockPrerequisite: "Goodbye Summer Pack",
  },
  {
    name: "Jötunnbane",
    type: "Axe",
    tier: 11,
    unlockPrerequisite: "Valhalla Superior Pack",
  },
  { name: "Crescent of Conquest", type: "Axe", tier: 12 },
  {
    name: "Onyx King Axe",
    type: "Axe",
    tier: 12,
    unlockPrerequisite: "Checkmate Superior Pack",
  },
  {
    name: "Lover's Quarrel",
    type: "Axe",
    tier: 12,
    unlockPrerequisite: "Valentine 2023 Mega Pack",
  },
  {
    name: "Apex Goraxe",
    type: "Axe",
    tier: 12,
    unlockPrerequisite: "Jurassic Pack",
  },
  { name: "Edge Eternal", type: "Axe", tier: 13 },
  { name: "Shiv", type: "Dagger", tier: 1 },
  {
    name: "Ice Pick",
    type: "Dagger",
    tier: 1,
    unlockPrerequisite: "Wooden Chest",
  },
  { name: "Swift Blade", type: "Dagger", tier: 2 },
  {
    name: "Kunai",
    type: "Dagger",
    tier: 2,
    unlockPrerequisite: "Starter Pack",
  },
  { name: "Stealth Knife", type: "Dagger", tier: 3 },
  { name: "Balisong", type: "Dagger", tier: 4 },
  {
    name: "Erudite Vector",
    type: "Dagger",
    tier: 4,
    unlockPrerequisite: "Back to School Mega Pack",
  },
  { name: "Ritual Dagger", type: "Dagger", tier: 5 },
  {
    name: "Sokka's Boomerang",
    type: "Dagger",
    tier: 5,
    unlockPrerequisite: "Content Pass: Avatar 2021",
  },
  {
    name: "Assassin Tanto",
    type: "Dagger",
    tier: 5,
    unlockPrerequisite: "Champions Clash Pack",
  },
  { name: "Kingsguard", type: "Dagger", tier: 6 },
  {
    name: "Cloudwalker Chakram",
    type: "Dagger",
    tier: 6,
    unlockPrerequisite: "Year of the Ox Mega Pack",
  },
  { name: "Fishmonger", type: "Dagger", tier: 7 },
  {
    name: "Juniper's Trowel",
    type: "Dagger",
    tier: 7,
    unlockPrerequisite: "Junimay Mega Pack",
  },
  { name: "Troll Tooth", type: "Dagger", tier: 8 },
  {
    name: "Levia Fang",
    type: "Dagger",
    tier: 8,
    unlockPrerequisite: "Timeworn Chest",
  },
  { name: "Misericordia", type: "Dagger", tier: 9 },
  {
    name: "Sultan Dagger",
    type: "Dagger",
    tier: 9,
    unlockPrerequisite: "Sultan's Superior Offer",
  },
  {
    name: "Luxurious Poignard",
    type: "Dagger",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Ceremonial Katar", type: "Dagger", tier: 10 },
  {
    name: "Nightmare Fellblade",
    type: "Dagger",
    tier: 10,
    unlockPrerequisite: "Sunken Chest",
  },
  {
    name: "Swan's Edge",
    type: "Dagger",
    tier: 10,
    unlockPrerequisite: "Champions Clash Mega Pack",
  },
  {
    name: "Lucky Strike",
    type: "Dagger",
    tier: 10,
    unlockPrerequisite: "Sia's Superior Offer",
  },
  { name: "Heartseeker", type: "Dagger", tier: 11 },
  {
    name: "Last Breath",
    type: "Dagger",
    tier: 11,
    unlockPrerequisite: "Bleak Chest",
  },
  {
    name: "Nightwing Bolt",
    type: "Dagger",
    tier: 11,
    unlockPrerequisite: "Spooktober Mega Pack",
  },
  {
    name: "Kyoshi Warrior Fan",
    type: "Dagger",
    tier: 11,
    unlockPrerequisite: "Earth Kingdom Superior Pack",
  },
  {
    name: "Wiccan Dagger",
    type: "Dagger",
    tier: 11,
    unlockPrerequisite: "Wiccan Magic Mega Pack",
  },
  { name: "Sixth Sin", type: "Dagger", tier: 12 },
  {
    name: "Opulent Tecpatl",
    type: "Dagger",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Celesteel Knuckles",
    type: "Dagger",
    tier: 12,
    unlockPrerequisite: "Wastelanders Superior Pack",
  },
  {
    name: "Empress War Fan",
    type: "Dagger",
    tier: 12,
    unlockPrerequisite: "Lunar New Year Mega Pack",
  },
  { name: "Nocturne", type: "Dagger", tier: 13 },
  { name: "Cudgel", type: "Mace", tier: 1, unlockPrerequisite: "Carpenter" },
  { name: "Spiked Cudgel", type: "Mace", tier: 2 },
  {
    name: "Darkwood Branch",
    type: "Mace",
    tier: 2,
    unlockPrerequisite: "Wooden Chest",
  },
  { name: "Warhammer", type: "Mace", tier: 3 },
  {
    name: "Liberty Mace",
    type: "Mace",
    tier: 3,
    unlockPrerequisite: "Freedom Pack",
  },
  { name: "Morning Star", type: "Mace", tier: 4 },
  {
    name: "Inflatable Maul",
    type: "Mace",
    tier: 4,
    unlockPrerequisite: "Summertime Mega Pack",
  },
  { name: "Flanged Mace", type: "Mace", tier: 5 },
  {
    name: "First Morning Star",
    type: "Mace",
    tier: 5,
    unlockPrerequisite: "New Year Mega Pack",
  },
  { name: "Skull Crusher", type: "Mace", tier: 6 },
  {
    name: "Troublin Bludgeon",
    type: "Mace",
    tier: 6,
    unlockPrerequisite: "Troublin Trouble Mega Pack",
  },
  { name: "Evening Star", type: "Mace", tier: 7 },
  {
    name: "Meteor Hammer",
    type: "Mace",
    tier: 7,
    unlockPrerequisite: "Ancient Chest",
  },
  {
    name: "Button Masher",
    type: "Mace",
    tier: 7,
    unlockPrerequisite: "Retro Arcade Mega Pack",
  },
  { name: "Powder Keg", type: "Mace", tier: 8 },
  {
    name: "Whack-O'-Lantern",
    type: "Mace",
    tier: 8,
    unlockPrerequisite: "Halloween Pack",
  },
  {
    name: "Peppermint Mallet",
    type: "Mace",
    tier: 8,
    unlockPrerequisite: "Holiday Pack",
  },
  { name: "Tenderizer", type: "Mace", tier: 9 },
  {
    name: "Wallace Mallet",
    type: "Mace",
    tier: 9,
    unlockPrerequisite: "Humble Beginnings Pack",
  },
  {
    name: "Striped Star",
    type: "Mace",
    tier: 9,
    unlockPrerequisite: "4th of July Superior Pack",
  },
  { name: "Nautilus", type: "Mace", tier: 10 },
  {
    name: "Opulent Maul",
    type: "Mace",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Mundra's Masher",
    type: "Mace",
    tier: 10,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  { name: "Thorium Hammer", type: "Mace", tier: 11 },
  {
    name: "Sunglow Impact",
    type: "Mace",
    tier: 11,
    unlockPrerequisite: "Bleak Chest",
  },
  {
    name: "Gaia Maul",
    type: "Mace",
    tier: 11,
    unlockPrerequisite: "Gaia's Mega Pack",
  },
  {
    name: "Sokka's Club",
    type: "Mace",
    tier: 11,
    unlockPrerequisite: "Water & Earth Mega Pack",
  },
  { name: "Mjölnir", type: "Mace", tier: 12 },
  {
    name: "Eggshell Smasher",
    type: "Mace",
    tier: 12,
    unlockPrerequisite: "Bunbun's Mega Pack",
  },
  {
    name: "Merry Christmace",
    type: "Mace",
    tier: 12,
    unlockPrerequisite: "Holiday 2022 Mega Pack",
  },
  { name: "Crag Guardian", type: "Mace", tier: 13 },
  {
    name: "Smash Hit",
    type: "Mace",
    tier: 13,
    unlockPrerequisite: "Music Mega Pack",
  },
  { name: "Javelin", type: "Spear", tier: 1 },
  { name: "Hunting Spear", type: "Spear", tier: 2 },
  { name: "Bladed Spear", type: "Spear", tier: 3 },
  {
    name: "Sturdy Pitchfork",
    type: "Spear",
    tier: 3,
    unlockPrerequisite: "Harvest Season Pack",
  },
  { name: "Ranseur", type: "Spear", tier: 4 },
  { name: "Trishula", type: "Spear", tier: 5 },
  {
    name: "Bunbun Lance",
    type: "Spear",
    tier: 5,
    unlockPrerequisite: "Lunar New Year Pack",
  },
  {
    name: "Warlord Halberd",
    type: "Spear",
    tier: 5,
    unlockPrerequisite: "Bunbun's Mega Pack",
  },
  { name: "Spetum", type: "Spear", tier: 6 },
  {
    name: "Triton Lance",
    type: "Spear",
    tier: 6,
    unlockPrerequisite: "Limestone Chest",
  },
  {
    name: "Cu Chulainn's Lance",
    type: "Spear",
    tier: 6,
    unlockPrerequisite: "Celtic Attire Mega Pack",
  },
  { name: "Royal Halberd", type: "Spear", tier: 7 },
  {
    name: "Twicicle Javelin",
    type: "Spear",
    tier: 7,
    unlockPrerequisite: "Aurora Mega Pack",
  },
  {
    name: "Warrior Assegai",
    type: "Spear",
    tier: 7,
    unlockPrerequisite: "Ancient Warrior Mega Pack",
  },
  { name: "Champion Lance", type: "Spear", tier: 8 },
  {
    name: "Sunset Yari",
    type: "Spear",
    tier: 8,
    unlockPrerequisite: "Tsukimi Festival Mega Pack",
  },
  { name: "Wyvern Glaive", type: "Spear", tier: 9 },
  {
    name: "Hoartooth Lance",
    type: "Spear",
    tier: 9,
    unlockPrerequisite: "Worker Duo Mega Pack",
  },
  {
    name: "Luxurious Spear",
    type: "Spear",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Stellaria", type: "Spear", tier: 10 },
  {
    name: "Longinus",
    type: "Spear",
    tier: 10,
    unlockPrerequisite: "Sunken Chest",
  },
  {
    name: "Birdbane Halberd",
    type: "Spear",
    tier: 10,
    unlockPrerequisite: "Thanksgiving Superior Offer",
  },
  { name: "Titania's Gift", type: "Spear", tier: 11 },
  {
    name: "Jester Jouster",
    type: "Spear",
    tier: 11,
    unlockPrerequisite: "Circus Superior Pack",
  },
  {
    name: "Holy Night Lance",
    type: "Spear",
    tier: 11,
    unlockPrerequisite: "Merry Christmas Mega Pack",
  },
  { name: "Heaven's Wrath", type: "Spear", tier: 12 },
  {
    name: "Propeller-Pike",
    type: "Spear",
    tier: 12,
    unlockPrerequisite: "Airship Superior Pack",
  },
  {
    name: "Pokey Parasol",
    type: "Spear",
    tier: 12,
    unlockPrerequisite: "Beach Party Pack",
  },
  {
    name: "Opulent Halberd",
    type: "Spear",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Blackened Bardiche", type: "Spear", tier: 13 },
  {
    name: "Riptide",
    type: "Spear",
    tier: 13,
    unlockPrerequisite: "Void Chest",
  },
  { name: "Training Bow", type: "Bow", tier: 1 },
  {
    name: "Tailwind",
    type: "Bow",
    tier: 1,
    unlockPrerequisite: "Wooden Chest",
  },
  { name: "Elmwood Bow", type: "Bow", tier: 2 },
  { name: "Reflex Bow", type: "Bow", tier: 3 },
  {
    name: "Grand Harp",
    type: "Bow",
    tier: 3,
    unlockPrerequisite: "Sia's Offer Pack",
  },
  { name: "Compound Bow", type: "Bow", tier: 4 },
  {
    name: "Mundra's Hornbow",
    type: "Bow",
    tier: 4,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  { name: "Deadeye", type: "Bow", tier: 5 },
  {
    name: "Hallowed Willow",
    type: "Bow",
    tier: 5,
    unlockPrerequisite: "Spooktober Mega Pack",
  },
  { name: "Raptoria", type: "Bow", tier: 6 },
  {
    name: "Quetzal Wing",
    type: "Bow",
    tier: 6,
    unlockPrerequisite: "Limestone Chest",
  },
  { name: "L'Arabesque", type: "Bow", tier: 7 },
  {
    name: "Hotshot Bowgun",
    type: "Bow",
    tier: 7,
    unlockPrerequisite: "Wild West Mega Pack",
  },
  { name: "Yumi", type: "Bow", tier: 8 },
  {
    name: "Cupid Bow",
    type: "Bow",
    tier: 8,
    unlockPrerequisite: "Valentine's Day Pack",
  },
  { name: "Bramblebane", type: "Bow", tier: 9 },
  {
    name: "Maplewood Gale",
    type: "Bow",
    tier: 9,
    unlockPrerequisite: "Autumn Mega Pack",
  },
  { name: "Gemini Strike", type: "Bow", tier: 10 },
  {
    name: "Jolly Ranger",
    type: "Bow",
    tier: 10,
    unlockPrerequisite: "Christmas Mega Pack",
  },
  { name: "Stormrend", type: "Bow", tier: 11 },
  {
    name: "Opulent Longbow",
    type: "Bow",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Pinata Hunter",
    type: "Bow",
    tier: 11,
    unlockPrerequisite: "Cinco De Mayo 2 Mega Pack",
  },
  {
    name: "Rising Star",
    type: "Bow",
    tier: 11,
    unlockPrerequisite: "New Year Mega Pack",
  },
  {
    name: "Boughwrought Bow",
    type: "Bow",
    tier: 11,
    unlockPrerequisite: "Swamp Superior Pack",
  },
  { name: "Olympus", type: "Bow", tier: 12 },
  {
    name: "Power Flipper",
    type: "Bow",
    tier: 12,
    unlockPrerequisite: "Retro Arcade Mega Pack",
  },
  {
    name: "Elite Pathfinder",
    type: "Bow",
    tier: 12,
    unlockPrerequisite: "Thanksgiving Superior Pack",
  },
  { name: "Grand Monarque", type: "Bow", tier: 13 },
  {
    name: "Earthstrung Wings",
    type: "Bow",
    tier: 13,
    unlockPrerequisite: "Void Chest",
  },
  {
    name: "Jindai Zakura",
    type: "Bow",
    tier: 13,
    unlockPrerequisite: "Sakura Mega Pack",
  },
  {
    name: "Carved Branch",
    type: "Staff",
    tier: 1,
    unlockPrerequisite: "Carpenter",
  },
  { name: "Sturdy Cane", type: "Staff", tier: 2 },
  { name: "Oak Staff", type: "Staff", tier: 3 },
  {
    name: "Owl Perch",
    type: "Staff",
    tier: 3,
    unlockPrerequisite: "Lilu's Offer Pack",
  },
  {
    name: "Luxurious Stick",
    type: "Staff",
    tier: 3,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Bo Staff", type: "Staff", tier: 4 },
  {
    name: "Apprentice Staff",
    type: "Staff",
    tier: 4,
    unlockPrerequisite: "Deluxe Pack",
  },
  { name: "Jade Scepter", type: "Staff", tier: 5 },
  {
    name: "Amber Staff",
    type: "Staff",
    tier: 5,
    unlockPrerequisite: "Slimy Chest",
  },
  {
    name: "Wiccan Broomstick",
    type: "Staff",
    tier: 5,
    unlockPrerequisite: "Wiccan Magic Mega Pack",
  },
  { name: "Wizard Staff", type: "Staff", tier: 6 },
  {
    name: "Staff of Seasons",
    type: "Staff",
    tier: 6,
    unlockPrerequisite: "Thanksgiving Pack",
  },
  { name: "Celestial Staff", type: "Staff", tier: 7 },
  {
    name: "Mundra's Scepter",
    type: "Staff",
    tier: 7,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  { name: "Imperial Aquila", type: "Staff", tier: 8 },
  {
    name: "Phoenix Staff",
    type: "Staff",
    tier: 8,
    unlockPrerequisite: "Timeworn Chest",
  },
  {
    name: "Fluted Chime",
    type: "Staff",
    tier: 8,
    unlockPrerequisite: "Music Mega Pack",
  },
  { name: "Transcendence", type: "Staff", tier: 9 },
  {
    name: "Tidebringer",
    type: "Staff",
    tier: 9,
    unlockPrerequisite: "Forsaken Chest",
  },
  {
    name: "Zesty Scepter",
    type: "Staff",
    tier: 9,
    unlockPrerequisite: "Summertime Mega Pack",
  },
  { name: "Seraphim", type: "Staff", tier: 10 },
  {
    name: "Staff of Merriment",
    type: "Staff",
    tier: 10,
    unlockPrerequisite: "Christmas Superior Offer",
  },
  { name: "Penumbra", type: "Staff", tier: 11 },
  {
    name: "Ice Queen's Scepter",
    type: "Staff",
    tier: 11,
    unlockPrerequisite: "Aurora Mega Pack",
  },
  {
    name: "Heartcaptor's Staff",
    type: "Staff",
    tier: 11,
    unlockPrerequisite: "True Love Mega Pack",
  },
  { name: "Scepter of Xolimnul", type: "Staff", tier: 12 },
  {
    name: "Opulent Staff",
    type: "Staff",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Soulbinder Staff",
    type: "Staff",
    tier: 12,
    unlockPrerequisite: "Immortal Mega Pack",
  },
  {
    name: "Pharaoh's Ankh",
    type: "Staff",
    tier: 12,
    unlockPrerequisite: "Pharaoh Superior Pack",
  },
  { name: "Cloud Nine", type: "Staff", tier: 13 },
  {
    name: "Gravity Controller",
    type: "Staff",
    tier: 13,
    unlockPrerequisite: "Void Chest",
  },
  {
    name: "Baton",
    type: "Wand",
    tier: 1,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Elvenwood Wand",
    type: "Wand",
    tier: 2,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Hexer's Wand",
    type: "Wand",
    tier: 3,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Steel Rod",
    type: "Wand",
    tier: 4,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Star Rod",
    type: "Wand",
    tier: 5,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Peppermint Cane",
    type: "Wand",
    tier: 5,
    unlockPrerequisite: "Christmas Superior Offer",
  },
  {
    name: "Sylvanel",
    type: "Wand",
    tier: 6,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Chōchin Gohei",
    type: "Wand",
    tier: 6,
    unlockPrerequisite: "Tsukimi Superior Pack",
  },
  {
    name: "Ruby Wand",
    type: "Wand",
    tier: 7,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Owl Wing Wand",
    type: "Wand",
    tier: 7,
    unlockPrerequisite: "Champions Superior Offer",
  },
  {
    name: "Wand of Midas",
    type: "Wand",
    tier: 8,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Evergreen Wand",
    type: "Wand",
    tier: 9,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Equinox Rod",
    type: "Wand",
    tier: 9,
    unlockPrerequisite: "Fall Superior Pack",
  },
  {
    name: "Astral Conductor",
    type: "Wand",
    tier: 10,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Grimar's Grand Wand",
    type: "Wand",
    tier: 10,
    unlockPrerequisite: "Mystic Superior Offer",
  },
  {
    name: "Draconic Eyestalk",
    type: "Wand",
    tier: 11,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Opulent Wand",
    type: "Wand",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Moonlight Wand",
    type: "Wand",
    tier: 11,
    unlockPrerequisite: "Moon Festival Superior Pack",
  },
  {
    name: "Herald of the End",
    type: "Wand",
    tier: 12,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Ivory Queen Rod",
    type: "Wand",
    tier: 12,
    unlockPrerequisite: "Checkmate Superior Pack",
  },
  {
    name: "Fork of Roasting",
    type: "Wand",
    tier: 12,
    unlockPrerequisite: "Sugar Shack Superior Pack",
  },
  {
    name: "Pyroquartz Rod",
    type: "Wand",
    tier: 13,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Light Crossbow",
    type: "Crossbow",
    tier: 1,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Hand Crossbow",
    type: "Crossbow",
    tier: 2,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Arbalest",
    type: "Crossbow",
    tier: 3,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Heavy Crossbow",
    type: "Crossbow",
    tier: 4,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Cluckthrower",
    type: "Crossbow",
    tier: 4,
    unlockPrerequisite: "Thanksgiving Superior Offer",
  },
  {
    name: "Hunter's Crossbow",
    type: "Crossbow",
    tier: 5,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Scorpio",
    type: "Crossbow",
    tier: 6,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Primitech Slingshot",
    type: "Crossbow",
    tier: 6,
    unlockPrerequisite: "Troublin Superior Pack",
  },
  {
    name: "Double Crossbow",
    type: "Crossbow",
    tier: 7,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Chu-Ko-Nu",
    type: "Crossbow",
    tier: 8,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Dra-Ko-Nu",
    type: "Crossbow",
    tier: 8,
    unlockPrerequisite: "Dragon Siblings Superior Offer",
  },
  {
    name: "Triple Crossbow",
    type: "Crossbow",
    tier: 9,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Super Repeater",
    type: "Crossbow",
    tier: 10,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Nightwing Caster",
    type: "Crossbow",
    tier: 10,
    unlockPrerequisite: "Halloween Superior Offer",
  },
  {
    name: "Leviathan",
    type: "Crossbow",
    tier: 11,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Opulent Crossbow",
    type: "Crossbow",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Titan Crossbow",
    type: "Crossbow",
    tier: 11,
    unlockPrerequisite: "Reinhold's Secret Offer",
  },
  {
    name: "Godslayer Arbalest",
    type: "Crossbow",
    tier: 12,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Baross' Backup",
    type: "Crossbow",
    tier: 12,
    unlockPrerequisite: "Airship Superior Pack",
  },
  {
    name: "Primarosa",
    type: "Crossbow",
    tier: 13,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Pellet Gun",
    type: "Gun",
    tier: 1,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Handgun",
    type: "Gun",
    tier: 2,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Smoothbore",
    type: "Gun",
    tier: 3,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Long Rifle",
    type: "Gun",
    tier: 4,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Snowball Launcher",
    type: "Gun",
    tier: 4,
    unlockPrerequisite: "Winter Superior Offer",
  },
  {
    name: "Blunderbuss",
    type: "Gun",
    tier: 5,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Boomstick",
    type: "Gun",
    tier: 6,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Banana Gun",
    type: "Gun",
    tier: 6,
    unlockPrerequisite: "Fruity Superior Pack",
  },
  {
    name: "Pellet Popper",
    type: "Gun",
    tier: 6,
    unlockPrerequisite: "Arcade 2023 Superior Pack",
  },
  {
    name: "Kenora Mk. IV",
    type: "Gun",
    tier: 7,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Prototype Gatling",
    type: "Gun",
    tier: 8,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Dragonator",
    type: "Gun",
    tier: 9,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Handcask '65",
    type: "Gun",
    tier: 9,
    unlockPrerequisite: "Oktoberfest Superior Pack",
  },
  {
    name: "The Messenger",
    type: "Gun",
    tier: 10,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Oxen Impact",
    type: "Gun",
    tier: 10,
    unlockPrerequisite: "Year of the Ox Superior Offer",
  },
  {
    name: "Omega Disintegrator",
    type: "Gun",
    tier: 11,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Opulent Pistol",
    type: "Gun",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Dogbone Blaster",
    type: "Gun",
    tier: 11,
    unlockPrerequisite: "Dog Superior Pack",
  },
  {
    name: "Blackbeard's Cannon",
    type: "Gun",
    tier: 12,
    unlockPrerequisite: "Crafty Engineer Pack",
  },
  {
    name: "Hotshot Carbine",
    type: "Gun",
    tier: 12,
    unlockPrerequisite: "Wild West Superior Pack",
  },
  {
    name: "Gift Wrap Rifle",
    type: "Gun",
    tier: 12,
    unlockPrerequisite: "Holiday 2022 Superior Pack",
  },
  { name: "Vainglory", type: "Gun", tier: 13 },
  {
    name: "Sonic Trumpeteer",
    type: "Gun",
    tier: 13,
    unlockPrerequisite: "Music Superior Pack",
  },
  {
    name: "Mintyleaf Herb",
    type: "Herbal Medicine",
    tier: 1,
    unlockPrerequisite: "Herbalist",
  },
  { name: "Sweet Grass", type: "Herbal Medicine", tier: 2 },
  { name: "Moon Powder", type: "Herbal Medicine", tier: 3 },
  {
    name: "Magical Mistletoe",
    type: "Herbal Medicine",
    tier: 3,
    unlockPrerequisite: "Holiday Pack",
  },
  { name: "Healing Salve", type: "Herbal Medicine", tier: 4 },
  {
    name: "Venerable Oats",
    type: "Herbal Medicine",
    tier: 4,
    unlockPrerequisite: "Thanksgiving Mega Pack",
  },
  { name: "Silver Thistle", type: "Herbal Medicine", tier: 5 },
  {
    name: "Bountiful Harvest",
    type: "Herbal Medicine",
    tier: 5,
    unlockPrerequisite: "Harvest Season Pack",
  },
  {
    name: "Flint Corn Bundle",
    type: "Herbal Medicine",
    tier: 5,
    unlockPrerequisite: "Thanksgiving 2022 Mega Pack",
  },
  { name: "Bloodvine", type: "Herbal Medicine", tier: 6 },
  {
    name: "Fragrant Bouquet",
    type: "Herbal Medicine",
    tier: 6,
    unlockPrerequisite: "Worker Duo Mega Pack",
  },
  {
    name: "Lil' Cactus",
    type: "Herbal Medicine",
    tier: 6,
    unlockPrerequisite: "Wastelanders Mega Pack",
  },
  { name: "Mandragoroot", type: "Herbal Medicine", tier: 7 },
  {
    name: "Unwilting Rose",
    type: "Herbal Medicine",
    tier: 7,
    unlockPrerequisite: "True Love Mega Pack",
  },
  { name: "Wolf's Bane", type: "Herbal Medicine", tier: 8 },
  {
    name: "Mistpeak Bloom",
    type: "Herbal Medicine",
    tier: 8,
    unlockPrerequisite: "Timeworn Chest",
  },
  { name: "Yggdrasil Branch", type: "Herbal Medicine", tier: 9 },
  {
    name: "Luckiest Clover",
    type: "Herbal Medicine",
    tier: 9,
    unlockPrerequisite: "St. Patrick's Golden Offer",
  },
  {
    name: "Luxurious Panacea",
    type: "Herbal Medicine",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Wyrmblood Ointment", type: "Herbal Medicine", tier: 10 },
  {
    name: "Wild Oak Rose",
    type: "Herbal Medicine",
    tier: 10,
    unlockPrerequisite: "Wild Love Superior Offer",
  },
  { name: "Florae Daemonica", type: "Herbal Medicine", tier: 11 },
  {
    name: "Bleakspire Roots",
    type: "Herbal Medicine",
    tier: 11,
    unlockPrerequisite: "Bleak Chest",
  },
  {
    name: "Seltzer Surprise",
    type: "Herbal Medicine",
    tier: 11,
    unlockPrerequisite: "Circus Mega Pack",
  },
  {
    name: "Super Snack Pack",
    type: "Herbal Medicine",
    tier: 11,
    unlockPrerequisite: "Sweet Superior Pack",
  },
  { name: "Philosopher's Stone", type: "Herbal Medicine", tier: 12 },
  {
    name: "Sakura Infusion",
    type: "Herbal Medicine",
    tier: 12,
    unlockPrerequisite: "Cherry Blossom Superior Pack",
  },
  {
    name: "Opulent Decoction",
    type: "Herbal Medicine",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Premium Brand Jam",
    type: "Herbal Medicine",
    tier: 12,
    unlockPrerequisite: "Fruity Superior Pack",
  },
  { name: "Voidbloom Roots", type: "Herbal Medicine", tier: 13 },
  {
    name: "Slide Grease",
    type: "Herbal Medicine",
    tier: 13,
    unlockPrerequisite: "Music Superior Pack",
  },
  { name: "Warm Tea", type: "Potion", tier: 1 },
  { name: "Healing Potion", type: "Potion", tier: 2 },
  { name: "Magic Potion", type: "Potion", tier: 3 },
  {
    name: "Science Project",
    type: "Potion",
    tier: 3,
    unlockPrerequisite: "Back to School Pack",
  },
  { name: "XL Healing Potion", type: "Potion", tier: 4 },
  {
    name: "Elegant Tea Set",
    type: "Potion",
    tier: 4,
    unlockPrerequisite: "Victorian Spring Mega Pack",
  },
  { name: "XL Magic Potion", type: "Potion", tier: 5 },
  {
    name: "Titan Potion",
    type: "Potion",
    tier: 5,
    unlockPrerequisite: "Shop Titans Mega Pack",
  },
  {
    name: "Old Salt's Brew",
    type: "Potion",
    tier: 5,
    unlockPrerequisite: "Champion Clash Mega Pack",
  },
  { name: "Phoenix Tonic", type: "Potion", tier: 6 },
  {
    name: "Zesty Granita",
    type: "Potion",
    tier: 6,
    unlockPrerequisite: "Cinco De Mayo 2 Mega Pack",
  },
  { name: "Potion of Renewal", type: "Potion", tier: 7 },
  {
    name: "Bottled Mirth",
    type: "Potion",
    tier: 7,
    unlockPrerequisite: "Ancient Chest",
  },
  { name: "Fizzy Guzzle Bottle", type: "Potion", tier: 7 },
  { name: "Purple Bomb", type: "Potion", tier: 8 },
  {
    name: "Gourd Elixir",
    type: "Potion",
    tier: 8,
    unlockPrerequisite: "Thanksgiving Pack",
  },
  { name: "Naya's Special", type: "Potion", tier: 8 },
  { name: "Special Sazonado", type: "Potion", tier: 8 },
  { name: "Soulfire Extract", type: "Potion", tier: 9 },
  {
    name: "Tangy Decoction",
    type: "Potion",
    tier: 9,
    unlockPrerequisite: "Summertime Superior Pack",
  },
  {
    name: "Oak Essence",
    type: "Potion",
    tier: 9,
    unlockPrerequisite: "Worker Duo Superior Pack",
  },
  { name: "Gaia Tonic", type: "Potion", tier: 10 },
  {
    name: "Midnight Oil",
    type: "Potion",
    tier: 10,
    unlockPrerequisite: "Halloween Superior Offer",
  },
  {
    name: "Opulent Elixir",
    type: "Potion",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Distilled Nebula", type: "Potion", tier: 11 },
  {
    name: "Aurora Springwater",
    type: "Potion",
    tier: 11,
    unlockPrerequisite: "Aurora Superior Pack",
  },
  {
    name: "Nectar Pitcher",
    type: "Potion",
    tier: 11,
    unlockPrerequisite: "Swamp Survivor Mega Pack",
  },
  { name: "Ambrosia", type: "Potion", tier: 12 },
  {
    name: "Mundra's Remedy",
    type: "Potion",
    tier: 12,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Quintessence Purity",
    type: "Potion",
    tier: 12,
    unlockPrerequisite: "Molten Chest",
  },
  {
    name: "Supreme Sunscreen",
    type: "Potion",
    tier: 12,
    unlockPrerequisite: "Beach Party Superior Pack",
  },
  {
    name: "Maple Holy Grail",
    type: "Potion",
    tier: 12,
    unlockPrerequisite: "Sugar Shack Superior Pack",
  },
  { name: "Conqueror's Blood", type: "Potion", tier: 13 },
  {
    name: "Satchel of Essentials",
    type: "Potion",
    tier: 13,
    unlockPrerequisite: "Arcade Mega Pack",
  },
  {
    name: "Scroll of Sparks",
    type: "Spell",
    tier: 1,
    unlockPrerequisite: "Wizard",
  },
  {
    name: "Scroll of Cleansing",
    type: "Spell",
    tier: 1,
    unlockPrerequisite: "Wooden Chest",
  },
  { name: "Scroll of Armor", type: "Spell", tier: 2 },
  { name: "Scroll of Storms", type: "Spell", tier: 3 },
  { name: "Song of Valor", type: "Spell", tier: 4 },
  {
    name: "Correspondence",
    type: "Spell",
    tier: 4,
    unlockPrerequisite: "Victorian Mega Pack",
  },
  { name: "Monster Manual", type: "Spell", tier: 5 },
  {
    name: "Tome of the Night",
    type: "Spell",
    tier: 5,
    unlockPrerequisite: "Slimy Chest",
  },
  {
    name: "Tome of Knowledge",
    type: "Spell",
    tier: 5,
    unlockPrerequisite: "Back to School Pack",
  },
  { name: "Tome of Secrets", type: "Spell", tier: 6 },
  {
    name: "Naughty or Nice List",
    type: "Spell",
    tier: 6,
    unlockPrerequisite: "Holiday Pack",
  },
  { name: "Bagua Board", type: "Spell", tier: 7 },
  {
    name: "Firework Bundle",
    type: "Spell",
    tier: 7,
    unlockPrerequisite: "Freedom Pack",
  },
  {
    name: "Tale of the Unicorn",
    type: "Spell",
    tier: 7,
    unlockPrerequisite: "Polar Unicorn Mega Pack",
  },
  { name: "Tarot Deck", type: "Spell", tier: 8 },
  {
    name: "Scroll of Fortune",
    type: "Spell",
    tier: 8,
    unlockPrerequisite: "Fortune Mega Pack",
  },
  { name: "Grimoire Aeternum", type: "Spell", tier: 9 },
  {
    name: "Imperial Decree",
    type: "Spell",
    tier: 9,
    unlockPrerequisite: "Augustus II Mega Pack",
  },
  {
    name: "Luxurious Tablet",
    type: "Spell",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Ancestral Atlas", type: "Spell", tier: 10 },
  {
    name: "Prayer Book",
    type: "Spell",
    tier: 10,
    unlockPrerequisite: "Mystic Duo Mega Pack",
  },
  {
    name: "Curse of the Night",
    type: "Spell",
    tier: 10,
    unlockPrerequisite: "Content Pass: Halloween 2022",
  },
  {
    name: "Druidic Grimoire",
    type: "Spell",
    tier: 10,
    unlockPrerequisite: "Celtic Superior Offer",
  },
  { name: "Celestial Choir", type: "Spell", tier: 11 },
  {
    name: "Phoenix Litany",
    type: "Spell",
    tier: 11,
    unlockPrerequisite: "Bleak Chest",
  },
  {
    name: "Sealed Declaration",
    type: "Spell",
    tier: 11,
    unlockPrerequisite: "Liberty Superior Pack",
  },
  {
    name: "Tiger Emperor's Edict",
    type: "Spell",
    tier: 11,
    unlockPrerequisite: "Tiger Superior Pack",
  },
  {
    name: "Tome of All-Knowledge",
    type: "Spell",
    tier: 11,
    unlockPrerequisite: "Collection Book",
  },
  { name: "The Bound Beast", type: "Spell", tier: 12 },
  {
    name: "Pharaoh's Pact",
    type: "Spell",
    tier: 12,
    unlockPrerequisite: "Pharaoh Mega Pack",
  },
  {
    name: "Lost Star Chart",
    type: "Spell",
    tier: 12,
    unlockPrerequisite: "New Year 2023 Mega Pack",
  },
  {
    name: "Love Declaration",
    type: "Spell",
    tier: 12,
    unlockPrerequisite: "Valentine 2023 Superior Pack",
  },
  {
    name: "Opulent Incantation",
    type: "Spell",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Pandora's Box", type: "Spell", tier: 13 },
  {
    name: "Sealed Hurricane",
    type: "Spell",
    tier: 13,
    unlockPrerequisite: "Void Chest",
  },
  {
    name: "Breastplate",
    type: "Heavy Armor",
    tier: 1,
    unlockPrerequisite: "Intro Tutorial",
  },
  { name: "Iron Mail", type: "Heavy Armor", tier: 2 },
  { name: "Scale Armor", type: "Heavy Armor", tier: 3 },
  { name: "Hauberk", type: "Heavy Armor", tier: 4 },
  { name: "Knight Breastplate", type: "Heavy Armor", tier: 5 },
  {
    name: "Ceremonial Breastplate",
    type: "Heavy Armor",
    tier: 5,
    unlockPrerequisite: "Slimy Chest",
  },
  {
    name: "Centurion Armor",
    type: "Heavy Armor",
    tier: 5,
    unlockPrerequisite: "Augustus II Mega Pack",
  },
  { name: "Paladin Plate", type: "Heavy Armor", tier: 6 },
  {
    name: "Thorn Baron Armor",
    type: "Heavy Armor",
    tier: 6,
    unlockPrerequisite: "Bee's Knees Mega Pack",
  },
  {
    name: "Hive Guard Plate",
    type: "Heavy Armor",
    tier: 6,
    unlockPrerequisite: "Pumpkin Party Mega Pack",
  },
  { name: "Samurai Do", type: "Heavy Armor", tier: 7 },
  {
    name: "Brinewater Do",
    type: "Heavy Armor",
    tier: 7,
    unlockPrerequisite: "Ancient Chest",
  },
  {
    name: "Kyoshi Warrior Armor",
    type: "Heavy Armor",
    tier: 7,
    unlockPrerequisite: "Earth Kingdom Superior Pack",
  },
  {
    name: "Warlord Plate",
    type: "Heavy Armor",
    tier: 7,
    unlockPrerequisite: "Lunar New Year Pack",
  },
  { name: "General Plate", type: "Heavy Armor", tier: 8 },
  {
    name: "Landsknecht Plate",
    type: "Heavy Armor",
    tier: 8,
    unlockPrerequisite: "Oktoberfest Pack",
  },
  {
    name: "Santa's Guard Plate",
    type: "Heavy Armor",
    tier: 8,
    unlockPrerequisite: "Holiday 2022 Mega Pack",
  },
  { name: "Berserker Armor", type: "Heavy Armor", tier: 9 },
  {
    name: "Gaia Enforcer",
    type: "Heavy Armor",
    tier: 9,
    unlockPrerequisite: "Forsaken Chest",
  },
  {
    name: "Star-Spangled Plate",
    type: "Heavy Armor",
    tier: 9,
    unlockPrerequisite: "4th of July Pack",
  },
  { name: "Juggernaut Fortress", type: "Heavy Armor", tier: 10 },
  {
    name: "Amber Citadel",
    type: "Heavy Armor",
    tier: 10,
    unlockPrerequisite: "Sunken Chest",
  },
  {
    name: "Opulent Breastplate",
    type: "Heavy Armor",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Milesian Mail",
    type: "Heavy Armor",
    tier: 10,
    unlockPrerequisite: "Celtic Attire Mega Pack",
  },
  { name: "Celesteel Plate", type: "Heavy Armor", tier: 11 },
  {
    name: "Canid Plate",
    type: "Heavy Armor",
    tier: 11,
    unlockPrerequisite: "Dog's Fortune Mega Pack",
  },
  {
    name: "Fire Nation Armor",
    type: "Heavy Armor",
    tier: 11,
    unlockPrerequisite: "Fire Nation Superior Pack",
  },
  { name: "Vermilion Guard Plate", type: "Heavy Armor", tier: 12 },
  {
    name: "Oni Rōnin Armor",
    type: "Heavy Armor",
    tier: 12,
    unlockPrerequisite: "Tsukimi Superior Pack",
  },
  {
    name: "Tyrant Plate Armor",
    type: "Heavy Armor",
    tier: 12,
    unlockPrerequisite: "Haunted Castle Mega Pack",
  },
  {
    name: "Lost Warrior's Plate",
    type: "Heavy Armor",
    tier: 12,
    unlockPrerequisite: "Chronos Ruins Superior Pack",
  },
  { name: "Balefire Armor", type: "Heavy Armor", tier: 13 },
  {
    name: "Magmacore Plate",
    type: "Heavy Armor",
    tier: 13,
    unlockPrerequisite: "Void Chest",
  },
  { name: "Leather Armor", type: "Light Armor", tier: 1 },
  { name: "Gambeson", type: "Light Armor", tier: 2 },
  { name: "Doublet", type: "Light Armor", tier: 3 },
  { name: "Studded Armor", type: "Light Armor", tier: 4 },
  {
    name: "Blizzard Armor",
    type: "Light Armor",
    tier: 4,
    unlockPrerequisite: "Winter Festivities Mega Pack",
  },
  { name: "Hide Armor", type: "Light Armor", tier: 5 },
  {
    name: "Mundra's Tabard",
    type: "Light Armor",
    tier: 5,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Sky Pirate Outfit",
    type: "Light Armor",
    tier: 5,
    unlockPrerequisite: "Airship Riders Pack",
  },
  { name: "Savage Garb", type: "Light Armor", tier: 6 },
  {
    name: "Glade Guard Armor",
    type: "Light Armor",
    tier: 6,
    unlockPrerequisite: "Limestone Chest",
  },
  {
    name: "Pumpkin Armor",
    type: "Light Armor",
    tier: 6,
    unlockPrerequisite: "Halloween Pack",
  },
  { name: "Ninja Garb", type: "Light Armor", tier: 7 },
  {
    name: "Nightwing Mantle",
    type: "Light Armor",
    tier: 7,
    unlockPrerequisite: "Halloween Mega Pack",
  },
  { name: "Windrunner Armor", type: "Light Armor", tier: 8 },
  {
    name: "Sokka's Outfit",
    type: "Light Armor",
    tier: 8,
    unlockPrerequisite: "Water & Earth Mega Pack",
  },
  { name: "Drakeskin Armor", type: "Light Armor", tier: 9 },
  {
    name: "Smith Attire",
    type: "Light Armor",
    tier: 9,
    unlockPrerequisite: "Wallace Superior Pack",
  },
  { name: "Corsair Mantle", type: "Light Armor", tier: 10 },
  {
    name: "Swan's Garment",
    type: "Light Armor",
    tier: 10,
    unlockPrerequisite: "Champions Superior Offer",
  },
  {
    name: "Cloudwalker Armor",
    type: "Light Armor",
    tier: 10,
    unlockPrerequisite: "Year of the Ox Mega Pack",
  },
  { name: "Everdusk Lord Attire", type: "Light Armor", tier: 11 },
  {
    name: "Opulent Armor",
    type: "Light Armor",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Barkback's Armor",
    type: "Light Armor",
    tier: 11,
    unlockPrerequisite: "Troublin Trouble Mega Pack",
  },
  {
    name: "Cat Burglar Outfit",
    type: "Light Armor",
    tier: 11,
    unlockPrerequisite: "Cat's Luck Mega Pack",
  },
  { name: "Dawn Thief Uniform", type: "Light Armor", tier: 12 },
  {
    name: "Shroud of the Lost",
    type: "Light Armor",
    tier: 12,
    unlockPrerequisite: "Molten Chest",
  },
  {
    name: "Stylish Poncho",
    type: "Light Armor",
    tier: 12,
    unlockPrerequisite: "Cinco de Mayo 3 Mega Pack",
  },
  {
    name: "Desperado Outfit",
    type: "Light Armor",
    tier: 12,
    unlockPrerequisite: "Wild West Mega Pack",
  },
  { name: "Wildhunt Leathers", type: "Light Armor", tier: 13 },
  { name: "Shirt", type: "Clothes", tier: 1, unlockPrerequisite: "Tailor" },
  { name: "Black Robe", type: "Clothes", tier: 2 },
  { name: "Druid's Robe", type: "Clothes", tier: 3 },
  { name: "Disciple's Robe", type: "Clothes", tier: 4 },
  { name: "Scholar's Tunic", type: "Clothes", tier: 5 },
  {
    name: "Explorer's Outfit",
    type: "Clothes",
    tier: 5,
    unlockPrerequisite: "Explorer Pack",
  },
  {
    name: "Tailor Mantle",
    type: "Clothes",
    tier: 5,
    unlockPrerequisite: "Humble Beginnings Pack",
  },
  { name: "Witch's Outfit", type: "Clothes", tier: 6 },
  {
    name: "Vestal Raiments",
    type: "Clothes",
    tier: 6,
    unlockPrerequisite: "Limestone Chest",
  },
  {
    name: "Wizard Attire",
    type: "Clothes",
    tier: 6,
    unlockPrerequisite: "Mystic Duo Mega Pack",
  },
  { name: "Midnight Apparel", type: "Clothes", tier: 7 },
  {
    name: "Aang's Robe",
    type: "Clothes",
    tier: 7,
    unlockPrerequisite: "Fire & Air Mega Pack",
  },
  { name: "Shaman Vestment", type: "Clothes", tier: 8 },
  {
    name: "Cupid Robes",
    type: "Clothes",
    tier: 8,
    unlockPrerequisite: "Valentine 2023 Mega Pack",
  },
  {
    name: "Luxurious Attire",
    type: "Clothes",
    tier: 8,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Astravestimenta", type: "Clothes", tier: 9 },
  {
    name: "Ostara Vest",
    type: "Clothes",
    tier: 9,
    unlockPrerequisite: "Easter Mega Pack",
  },
  {
    name: "Desert Threads",
    type: "Clothes",
    tier: 9,
    unlockPrerequisite: "Sultan's Finest Mega Pack",
  },
  { name: "Archmage Raiments", type: "Clothes", tier: 10 },
  {
    name: "Republic Garments",
    type: "Clothes",
    tier: 10,
    unlockPrerequisite: "Republic Day Superior Offer",
  },
  { name: "Djinn Robes", type: "Clothes", tier: 11 },
  {
    name: "Moonlight Kimono",
    type: "Clothes",
    tier: 11,
    unlockPrerequisite: "Moon Festival Mega Pack",
  },
  {
    name: "Tiger Emperor's Robe",
    type: "Clothes",
    tier: 11,
    unlockPrerequisite: "Year of the Tiger Mega Pack",
  },
  { name: "Exarch Robes", type: "Clothes", tier: 12 },
  {
    name: "Soulbinder Regalia",
    type: "Clothes",
    tier: 12,
    unlockPrerequisite: "Immortal Superior Pack",
  },
  {
    name: "Opulent Vestment",
    type: "Clothes",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Garb of the Primordial",
    type: "Clothes",
    tier: 12,
    unlockPrerequisite: "Molten Chest",
  },
  {
    name: "Ice Queen's Silks",
    type: "Clothes",
    tier: 12,
    unlockPrerequisite: "Polar Unicorn Mega Pack",
  },
  { name: "Voidminster Habit", type: "Clothes", tier: 13 },
  { name: "Sturdy Cap", type: "Helmet", tier: 1 },
  { name: "Warrior Helmet", type: "Helmet", tier: 2 },
  { name: "Horned Helm", type: "Helmet", tier: 3 },
  { name: "Raider Helm", type: "Helmet", tier: 4 },
  { name: "Knight Heaume", type: "Helmet", tier: 5 },
  {
    name: "Brinewater Helm",
    type: "Helmet",
    tier: 5,
    unlockPrerequisite: "Slimy Chest",
  },
  {
    name: "Eagle Helm",
    type: "Helmet",
    tier: 5,
    unlockPrerequisite: "Freedom Pack",
  },
  {
    name: "Rex Chomper",
    type: "Helmet",
    tier: 5,
    unlockPrerequisite: "Jurassic Pack",
  },
  { name: "Paladin Helm", type: "Helmet", tier: 6 },
  {
    name: "Kodiak Helmet",
    type: "Helmet",
    tier: 6,
    unlockPrerequisite: "Wild Love Mega Pack",
  },
  {
    name: "Fire Nation Helm",
    type: "Helmet",
    tier: 6,
    unlockPrerequisite: "Fire Nation Superior Pack",
  },
  {
    name: "Crown of Tyranny",
    type: "Helmet",
    tier: 6,
    unlockPrerequisite: "Haunted Castle Mega Pack",
  },
  { name: "Samurai Kabuto", type: "Helmet", tier: 7 },
  {
    name: "Gladiator Helm",
    type: "Helmet",
    tier: 7,
    unlockPrerequisite: "Augustus Pack",
  },
  {
    name: "Sandcastle Protector",
    type: "Helmet",
    tier: 7,
    unlockPrerequisite: "Beach Party Pack",
  },
  { name: "General Heaume", type: "Helmet", tier: 8 },
  {
    name: "Crusader Helmet",
    type: "Helmet",
    tier: 8,
    unlockPrerequisite: "Timeworn Chest",
  },
  {
    name: "Warlord Helmet",
    type: "Helmet",
    tier: 8,
    unlockPrerequisite: "Lunar New Year Pack",
  },
  { name: "Berserker Helmet", type: "Helmet", tier: 9 },
  {
    name: "Centurion Helmet",
    type: "Helmet",
    tier: 9,
    unlockPrerequisite: "Augustus II Superior Pack",
  },
  { name: "Juggernaut Furnace", type: "Helmet", tier: 10 },
  {
    name: "Gobble Lord Helm",
    type: "Helmet",
    tier: 10,
    unlockPrerequisite: "Thanksgiving Mega Pack",
  },
  {
    name: "Opulent Heaume",
    type: "Helmet",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Celesteel Heaume", type: "Helmet", tier: 11 },
  {
    name: "Canid Helmet",
    type: "Helmet",
    tier: 11,
    unlockPrerequisite: "Dog Superior Pack",
  },
  {
    name: "Cupid's Heaume",
    type: "Helmet",
    tier: 11,
    unlockPrerequisite: "True Love Superior Pack",
  },
  { name: "Vermilion Guard Helm", type: "Helmet", tier: 12 },
  {
    name: "Onyx King Helm",
    type: "Helmet",
    tier: 12,
    unlockPrerequisite: "Checkmate Mega Pack",
  },
  {
    name: "Thorn Baron Helm",
    type: "Helmet",
    tier: 12,
    unlockPrerequisite: "Pumpkin Party Mega Pack",
  },
  { name: "Balefire Gaze", type: "Helmet", tier: 13 },
  {
    name: "Taishōgun Kabuto",
    type: "Helmet",
    tier: 13,
    unlockPrerequisite: "Sakura Superior Pack",
  },
  { name: "Leather Cap", type: "Rogue Hat", tier: 1 },
  {
    name: "Canopy Cap",
    type: "Rogue Hat",
    tier: 1,
    unlockPrerequisite: "Wooden Chest",
  },
  { name: "Brimmed Hat", type: "Rogue Hat", tier: 2 },
  { name: "Feathered Hat", type: "Rogue Hat", tier: 3 },
  { name: "Tricorn", type: "Rogue Hat", tier: 4 },
  { name: "Silk Hood", type: "Rogue Hat", tier: 5 },
  {
    name: "Santa's Elf Hat",
    type: "Rogue Hat",
    tier: 5,
    unlockPrerequisite: "Christmas Mega Pack",
  },
  {
    name: "Pharaoh's Nemes",
    type: "Rogue Hat",
    tier: 5,
    unlockPrerequisite: "Pharaoh Mega Pack",
  },
  { name: "Pirate Hat", type: "Rogue Hat", tier: 6 },
  {
    name: "Lovely Hat",
    type: "Rogue Hat",
    tier: 6,
    unlockPrerequisite: "Valentine's Day Pack",
  },
  { name: "Night Cowl", type: "Rogue Hat", tier: 7 },
  {
    name: "Nomad Veil",
    type: "Rogue Hat",
    tier: 7,
    unlockPrerequisite: "Ancient Chest",
  },
  {
    name: "Harvester's Hood",
    type: "Rogue Hat",
    tier: 7,
    unlockPrerequisite: "Harvest Season Pack",
  },
  { name: "Windrunner Hat", type: "Rogue Hat", tier: 8 },
  {
    name: "Blue Spirit Mask",
    type: "Rogue Hat",
    tier: 8,
    unlockPrerequisite: "Content Pass: Avatar 2021",
  },
  {
    name: "Musketeer Hat",
    type: "Rogue Hat",
    tier: 8,
    unlockPrerequisite: "Musketeer Mega Pack",
  },
  { name: "Drakeskin Mask", type: "Rogue Hat", tier: 9 },
  {
    name: "Storm Dragon Mask",
    type: "Rogue Hat",
    tier: 9,
    unlockPrerequisite: "Forsaken Chest",
  },
  {
    name: "Grand Tyrolean",
    type: "Rogue Hat",
    tier: 9,
    unlockPrerequisite: "Oktoberfest Superior Pack",
  },
  { name: "Corsair Tricorn", type: "Rogue Hat", tier: 10 },
  {
    name: "Republic Coiffe",
    type: "Rogue Hat",
    tier: 10,
    unlockPrerequisite: "Republic Day Mega Pack",
  },
  { name: "Everdusk Cowl", type: "Rogue Hat", tier: 11 },
  {
    name: "Abyssal Hood",
    type: "Rogue Hat",
    tier: 11,
    unlockPrerequisite: "Bleak Chest",
  },
  {
    name: "Rogue Sombrero",
    type: "Rogue Hat",
    tier: 11,
    unlockPrerequisite: "Cinco De Mayo 2 Superior Pack",
  },
  {
    name: "Cat Burglar Hood",
    type: "Rogue Hat",
    tier: 11,
    unlockPrerequisite: "Cat Superior Pack",
  },
  {
    name: "Opulent Sallet",
    type: "Rogue Hat",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Dawn Thief Cowl", type: "Rogue Hat", tier: 12 },
  {
    name: "Bunbun Masquerade",
    type: "Rogue Hat",
    tier: 12,
    unlockPrerequisite: "Bunbun's Superior Pack",
  },
  {
    name: "Dragonseeker Goggles",
    type: "Rogue Hat",
    tier: 12,
    unlockPrerequisite: "Airship Riders Pack",
  },
  {
    name: "Kitsune Spirit Mask",
    type: "Rogue Hat",
    tier: 12,
    unlockPrerequisite: "Tsukimi Festival Mega Pack",
  },
  { name: "Wildhunt Skull", type: "Rogue Hat", tier: 13 },
  { name: "Stitched Cone", type: "Magician Hat", tier: 1 },
  { name: "Black Cowl", type: "Magician Hat", tier: 2 },
  { name: "Druid Laurels", type: "Magician Hat", tier: 3 },
  {
    name: "Apprentice Tiara",
    type: "Magician Hat",
    tier: 3,
    unlockPrerequisite: "Advanced Pack",
  },
  { name: "Bronze Circlet", type: "Magician Hat", tier: 4 },
  { name: "Wizard Hat", type: "Magician Hat", tier: 5 },
  {
    name: "Hat of the Four Winds",
    type: "Magician Hat",
    tier: 5,
    unlockPrerequisite: "Slimy Chest",
  },
  {
    name: "Ostara Hat",
    type: "Magician Hat",
    tier: 5,
    unlockPrerequisite: "Easter Galore Mega Pack",
  },
  { name: "Witch Hat", type: "Magician Hat", tier: 6 },
  {
    name: "Waterproof Lilycap",
    type: "Magician Hat",
    tier: 6,
    unlockPrerequisite: "Champions Clash Mega Pack",
  },
  {
    name: "Owl Cowl",
    type: "Magician Hat",
    tier: 6,
    unlockPrerequisite: "Swamp Survivor Mega Pack",
  },
  { name: "Tactician Hat", type: "Magician Hat", tier: 7 },
  {
    name: "Summoner Hat",
    type: "Magician Hat",
    tier: 7,
    unlockPrerequisite: "Explorer Pack",
  },
  {
    name: "Ivory Queen Crown",
    type: "Magician Hat",
    tier: 7,
    unlockPrerequisite: "Checkmate Mega Pack",
  },
  { name: "Shaman Hat", type: "Magician Hat", tier: 8 },
  {
    name: "Luxurious Headdress",
    type: "Magician Hat",
    tier: 8,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Astral Hat", type: "Magician Hat", tier: 9 },
  {
    name: "Raven Mask",
    type: "Magician Hat",
    tier: 9,
    unlockPrerequisite: "Victorian Superior Pack",
  },
  {
    name: "Spellward Hat",
    type: "Magician Hat",
    tier: 9,
    unlockPrerequisite: "Back to School Superior Offer",
  },
  { name: "Opal Diadem", type: "Magician Hat", tier: 10 },
  {
    name: "Night Crown",
    type: "Magician Hat",
    tier: 10,
    unlockPrerequisite: "Halloween Mega Pack",
  },
  { name: "Djinn Veil", type: "Magician Hat", tier: 11 },
  {
    name: "Elegant Top Hat",
    type: "Magician Hat",
    tier: 11,
    unlockPrerequisite: "Victorian Spring Superior Offer",
  },
  {
    name: "Ice Queen's Summer Hat",
    type: "Magician Hat",
    tier: 11,
    unlockPrerequisite: "Snow Day Superior Pack",
  },
  { name: "Exarch Mitre", type: "Magician Hat", tier: 12 },
  {
    name: "Sakura Eboshi",
    type: "Magician Hat",
    tier: 12,
    unlockPrerequisite: "Cherry Blossoms Mega Pack",
  },
  {
    name: "Opulent Headdress",
    type: "Magician Hat",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Phoenix Crest",
    type: "Magician Hat",
    tier: 12,
    unlockPrerequisite: "Molten Chest",
  },
  {
    name: "Empress Hairpins",
    type: "Magician Hat",
    tier: 12,
    unlockPrerequisite: "Bunny Superior Pack",
  },
  { name: "Voidminster Hat", type: "Magician Hat", tier: 13 },
  {
    name: "Elysium Halo",
    type: "Magician Hat",
    tier: 13,
    unlockPrerequisite: "Void Chest",
  },
  { name: "Iron Armguards", type: "Gauntlets", tier: 1 },
  { name: "Plated Gauntlets", type: "Gauntlets", tier: 2 },
  { name: "Warrior Gauntlets", type: "Gauntlets", tier: 3 },
  { name: "Demi Gauntlets", type: "Gauntlets", tier: 4 },
  {
    name: "Pumpkin Gauntlets",
    type: "Gauntlets",
    tier: 4,
    unlockPrerequisite: "Halloween Pack",
  },
  { name: "Knight Gauntlets", type: "Gauntlets", tier: 5 },
  {
    name: "Santa's Guard Gauntlets",
    type: "Gauntlets",
    tier: 5,
    unlockPrerequisite: "Merry Christmas Mega Pack",
  },
  {
    name: "Hands of the Fifth",
    type: "Gauntlets",
    tier: 5,
    unlockPrerequisite: "Content Pass: Cinco de Mayo 2022",
  },
  { name: "Paladin Gauntlets", type: "Gauntlets", tier: 6 },
  {
    name: "Sungrasp Gauntlets",
    type: "Gauntlets",
    tier: 6,
    unlockPrerequisite: "Limestone Chest",
  },
  {
    name: "Landsknecht Gauntlets",
    type: "Gauntlets",
    tier: 6,
    unlockPrerequisite: "Oktoberfest Pack",
  },
  { name: "Samurai Kote", type: "Gauntlets", tier: 7 },
  {
    name: "Republic Gauntlets",
    type: "Gauntlets",
    tier: 7,
    unlockPrerequisite: "Republic Day Mega Pack",
  },
  {
    name: "Fruity Gauntlets",
    type: "Gauntlets",
    tier: 7,
    unlockPrerequisite: "Fruity Mega Pack",
  },
  { name: "General Gauntlets", type: "Gauntlets", tier: 8 },
  { name: "Berserker Gauntlets", type: "Gauntlets", tier: 9 },
  {
    name: "Luxurious Gauntlets",
    type: "Gauntlets",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Juggernaut Grip", type: "Gauntlets", tier: 10 },
  {
    name: "Winter's Touch",
    type: "Gauntlets",
    tier: 10,
    unlockPrerequisite: "Winter Festivities Mega Pack",
  },
  { name: "Celesteel Gauntlets", type: "Gauntlets", tier: 11 },
  {
    name: "Gaia's Hold",
    type: "Gauntlets",
    tier: 11,
    unlockPrerequisite: "Gaia's Superior Offer",
  },
  {
    name: "Vanguard Gauntlets",
    type: "Gauntlets",
    tier: 11,
    unlockPrerequisite: "Goodbye Summer Superior Pack",
  },
  {
    name: "Huscarl Gauntlets",
    type: "Gauntlets",
    tier: 11,
    unlockPrerequisite: "Valhalla Mega Pack",
  },
  { name: "Vermilion Guard Might", type: "Gauntlets", tier: 12 },
  {
    name: "Goon's Facesmackers",
    type: "Gauntlets",
    tier: 12,
    unlockPrerequisite: "Wastelanders Mega Pack",
  },
  {
    name: "Opulent Dracofists",
    type: "Gauntlets",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Tyrant Fists",
    type: "Gauntlets",
    tier: 12,
    unlockPrerequisite: "Castle Superior Pack",
  },
  { name: "Balefire Gauntlets", type: "Gauntlets", tier: 13 },
  {
    name: "Power Gauntlet",
    type: "Gauntlets",
    tier: 13,
    unlockPrerequisite: "Arcade 2023 Superior Pack",
  },
  {
    name: "Leather Gloves",
    type: "Gloves",
    tier: 1,
    unlockPrerequisite: "Tailor",
  },
  { name: "Bracers", type: "Gloves", tier: 2 },
  { name: "Thief's Gloves", type: "Gloves", tier: 3 },
  {
    name: "Swift Mitts",
    type: "Gloves",
    tier: 3,
    unlockPrerequisite: "Frozen Chest",
  },
  {
    name: "Patchleather Bracers",
    type: "Gloves",
    tier: 3,
    unlockPrerequisite: "Thanksgiving Pack",
  },
  { name: "Studded Gloves", type: "Gloves", tier: 4 },
  {
    name: "Regal Bangles",
    type: "Gloves",
    tier: 4,
    unlockPrerequisite: "Year of the Tiger Mega Pack",
  },
  { name: "Elven Vambraces", type: "Gloves", tier: 5 },
  {
    name: "Ostara Gloves",
    type: "Gloves",
    tier: 5,
    unlockPrerequisite: "Easter Mega Pack",
  },
  { name: "Savage Claws", type: "Gloves", tier: 6 },
  {
    name: "Black Wyrm Claws",
    type: "Gloves",
    tier: 6,
    unlockPrerequisite: "Limestone Chest",
  },
  { name: "Ninja Gloves", type: "Gloves", tier: 7 },
  {
    name: "Cat Burglar Claws",
    type: "Gloves",
    tier: 7,
    unlockPrerequisite: "Cat's Luck Mega Pack",
  },
  { name: "Windrunner Gloves", type: "Gloves", tier: 8 },
  {
    name: "Sakura Cuffs",
    type: "Gloves",
    tier: 8,
    unlockPrerequisite: "Sakura Mega Pack",
  },
  { name: "Drakeskin Gloves", type: "Gloves", tier: 9 },
  {
    name: "Mountain Man Mitts",
    type: "Gloves",
    tier: 9,
    unlockPrerequisite: "Oktoberfest Mega Pack",
  },
  { name: "Corsair Gloves", type: "Gloves", tier: 10 },
  {
    name: "Fortunate Gloves",
    type: "Gloves",
    tier: 10,
    unlockPrerequisite: "Fortune Mega Pack",
  },
  {
    name: "Opulent Grasp",
    type: "Gloves",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Everdusk Gloves", type: "Gloves", tier: 11 },
  {
    name: "Raptor Wings",
    type: "Gloves",
    tier: 11,
    unlockPrerequisite: "Pollux Mega Pack",
  },
  {
    name: "Nightwing Vambraces",
    type: "Gloves",
    tier: 11,
    unlockPrerequisite: "Spooktober Superior Pack",
  },
  { name: "Dawn Thief's Touch", type: "Gloves", tier: 12 },
  {
    name: "Swindler's Fingers",
    type: "Gloves",
    tier: 12,
    unlockPrerequisite: "Molten Chest",
  },
  {
    name: "Gloves of Rhythm",
    type: "Gloves",
    tier: 12,
    unlockPrerequisite: "Cinco de Mayo 3 Superior Pack",
  },
  {
    name: "Gants d'Artagnan",
    type: "Gloves",
    tier: 12,
    unlockPrerequisite: "Musketeer Superior Pack",
  },
  { name: "Wildhunt Gloves", type: "Gloves", tier: 13 },
  { name: "Shin Guards", type: "Heavy Footwear", tier: 1 },
  { name: "Long Boots", type: "Heavy Footwear", tier: 2 },
  { name: "Iron Greaves", type: "Heavy Footwear", tier: 3 },
  {
    name: "Hero's Boots",
    type: "Heavy Footwear",
    tier: 3,
    unlockPrerequisite: "Hero Pack",
  },
  { name: "Reinforced Greaves", type: "Heavy Footwear", tier: 4 },
  {
    name: "Plated Squeakers",
    type: "Heavy Footwear",
    tier: 4,
    unlockPrerequisite: "Circus Mega Pack",
  },
  { name: "Knight Sollerets", type: "Heavy Footwear", tier: 5 },
  {
    name: "Cindersole",
    type: "Heavy Footwear",
    tier: 5,
    unlockPrerequisite: "Slimy Chest",
  },
  {
    name: "Warlord Boots",
    type: "Heavy Footwear",
    tier: 5,
    unlockPrerequisite: "Content Pass: Year of the Tiger",
  },
  { name: "Paladin Boots", type: "Heavy Footwear", tier: 6 },
  {
    name: "Canid Paws",
    type: "Heavy Footwear",
    tier: 6,
    unlockPrerequisite: "Dog's Fortune Mega Pack",
  },
  { name: "Samurai Haidate", type: "Heavy Footwear", tier: 7 },
  {
    name: "Topaz Greaves",
    type: "Heavy Footwear",
    tier: 7,
    unlockPrerequisite: "Dungeon Explorer Offer",
  },
  { name: "General Greaves", type: "Heavy Footwear", tier: 8 },
  { name: "Berserker Stompers", type: "Heavy Footwear", tier: 9 },
  {
    name: "Luxurious Boots",
    type: "Heavy Footwear",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  {
    name: "Vanguard Greaves",
    type: "Heavy Footwear",
    tier: 9,
    unlockPrerequisite: "Fall Superior Pack",
  },
  { name: "Juggernaut Greaves", type: "Heavy Footwear", tier: 10 },
  {
    name: "Bunbun Booties",
    type: "Heavy Footwear",
    tier: 10,
    unlockPrerequisite: "Easter Superior Offer",
  },
  {
    name: "Greaves of the Fifth",
    type: "Heavy Footwear",
    tier: 10,
    unlockPrerequisite: "Content Pass: Cinco de Mayo 2022",
  },
  { name: "Celesteel Boots", type: "Heavy Footwear", tier: 11 },
  {
    name: "Star-Spangled Greaves",
    type: "Heavy Footwear",
    tier: 11,
    unlockPrerequisite: "Liberty Mega Pack",
  },
  {
    name: "Santa's Guard Boots",
    type: "Heavy Footwear",
    tier: 11,
    unlockPrerequisite: "Merry Christmas Superior Pack",
  },
  { name: "Vermilion Guard Greaves", type: "Heavy Footwear", tier: 12 },
  {
    name: "Boots of Zeal",
    type: "Heavy Footwear",
    tier: 12,
    unlockPrerequisite: "Molten Chest",
  },
  {
    name: "Fruity Booties",
    type: "Heavy Footwear",
    tier: 12,
    unlockPrerequisite: "Fruity Mega Pack",
  },
  {
    name: "Opulent Greaves",
    type: "Heavy Footwear",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Rex Stompers",
    type: "Heavy Footwear",
    tier: 12,
    unlockPrerequisite: "Jurassic Superior Pack",
  },
  { name: "Balefire Greaves", type: "Heavy Footwear", tier: 13 },
  {
    name: "Leather Boots",
    type: "Light Footwear",
    tier: 1,
    unlockPrerequisite: "Tailor",
  },
  {
    name: "Trailblazers",
    type: "Light Footwear",
    tier: 1,
    unlockPrerequisite: "Wooden Chest",
  },
  { name: "Flip-Flops", type: "Light Footwear", tier: 2 },
  { name: "Soft Shoes", type: "Light Footwear", tier: 3 },
  {
    name: "Legionnaire Sandals",
    type: "Light Footwear",
    tier: 3,
    unlockPrerequisite: "Augustus Pack",
  },
  { name: "Thief's Shoes", type: "Light Footwear", tier: 4 },
  {
    name: "Perennial Sandals",
    type: "Light Footwear",
    tier: 4,
    unlockPrerequisite: "Spring Festivities Pack",
  },
  { name: "Elven Shoes", type: "Light Footwear", tier: 5 },
  {
    name: "Moonlight Zōri",
    type: "Light Footwear",
    tier: 5,
    unlockPrerequisite: "Moon Festival Mega Pack",
  },
  { name: "Savage Stride", type: "Light Footwear", tier: 6 },
  {
    name: "Sakura Tabi",
    type: "Light Footwear",
    tier: 6,
    unlockPrerequisite: "Cherry Blossom Superior Pack",
  },
  {
    name: "Sultan Steps",
    type: "Light Footwear",
    tier: 6,
    unlockPrerequisite: "Sultan's Finest Mega Pack",
  },
  { name: "Ninja Tabi", type: "Light Footwear", tier: 7 },
  {
    name: "Nightwing Shoes",
    type: "Light Footwear",
    tier: 7,
    unlockPrerequisite: "Content Pass: Halloween 2022",
  },
  { name: "Windrunner Boots", type: "Light Footwear", tier: 8 },
  {
    name: "Alpine Stride",
    type: "Light Footwear",
    tier: 8,
    unlockPrerequisite: "Timeworn Chest",
  },
  { name: "Drakeskin Boots", type: "Light Footwear", tier: 9 },
  {
    name: "Plaguewalkers",
    type: "Light Footwear",
    tier: 9,
    unlockPrerequisite: "Forsaken Chest",
  },
  {
    name: "Shoes of Style",
    type: "Light Footwear",
    tier: 9,
    unlockPrerequisite: "Cinco De Mayo Superior Pack",
  },
  { name: "Corsair Boots", type: "Light Footwear", tier: 10 },
  {
    name: "Cloudwalker Steps",
    type: "Light Footwear",
    tier: 10,
    unlockPrerequisite: "Year of the Ox Superior Offer",
  },
  { name: "Everdusk Boots", type: "Light Footwear", tier: 11 },
  {
    name: "Raptor Talons",
    type: "Light Footwear",
    tier: 11,
    unlockPrerequisite: "Pollux Superior Pack",
  },
  {
    name: "Opulent Footwraps",
    type: "Light Footwear",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Dawn Thief's Path", type: "Light Footwear", tier: 12 },
  {
    name: "Desperado Spurs",
    type: "Light Footwear",
    tier: 12,
    unlockPrerequisite: "Wild West Superior Pack",
  },
  {
    name: "Hunter Moccasins",
    type: "Light Footwear",
    tier: 12,
    unlockPrerequisite: "Thanksgiving 2022 Mega Pack",
  },
  {
    name: "Fairy Sandals",
    type: "Light Footwear",
    tier: 12,
    unlockPrerequisite: "Junimay Mega Pack",
  },
  { name: "Wildhunt Sandals", type: "Light Footwear", tier: 13 },
  { name: "Wooden Shield", type: "Shield", tier: 1 },
  { name: "Heavy Buckler", type: "Shield", tier: 2 },
  { name: "Oaken Shield", type: "Shield", tier: 3 },
  { name: "Iron Shield", type: "Shield", tier: 4 },
  {
    name: "Aurum Ward",
    type: "Shield",
    tier: 4,
    unlockPrerequisite: "Frozen Chest",
  },
  { name: "Teardrop Shield", type: "Shield", tier: 5 },
  {
    name: "Imperial Scutum",
    type: "Shield",
    tier: 5,
    unlockPrerequisite: "Augustus Pack",
  },
  {
    name: "Champion Vigil",
    type: "Shield",
    tier: 5,
    unlockPrerequisite: "Champions Clash Pack",
  },
  { name: "Mythril Aspis", type: "Shield", tier: 6 },
  {
    name: "Raider Buckler",
    type: "Shield",
    tier: 6,
    unlockPrerequisite: "Valhalla Mega Pack",
  },
  {
    name: "Gaia Aegis",
    type: "Shield",
    tier: 6,
    unlockPrerequisite: "Gaia's Mega Pack",
  },
  { name: "Wyrmguard", type: "Shield", tier: 7 },
  {
    name: "Vanguard Buckler",
    type: "Shield",
    tier: 7,
    unlockPrerequisite: "Goodbye Summer Pack",
  },
  { name: "Ancestor Totem", type: "Shield", tier: 8 },
  { name: "Angelic Pavise", type: "Shield", tier: 9 },
  {
    name: "Prometheon",
    type: "Shield",
    tier: 9,
    unlockPrerequisite: "Forsaken Chest",
  },
  {
    name: "Milesian Shield",
    type: "Shield",
    tier: 9,
    unlockPrerequisite: "St. Patrick's Day Pack",
  },
  {
    name: "Bunbun Buckler",
    type: "Shield",
    tier: 9,
    unlockPrerequisite: "Easter Superior Pack",
  },
  {
    name: "Luxurious Aegis",
    type: "Shield",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Goldmane Guard", type: "Shield", tier: 10 },
  {
    name: "Emperor Wyrmguard",
    type: "Shield",
    tier: 10,
    unlockPrerequisite: "Dragon Siblings Mega Pack",
  },
  { name: "Bearded Paragon", type: "Shield", tier: 11 },
  {
    name: "Honeycomb Defender",
    type: "Shield",
    tier: 11,
    unlockPrerequisite: "Bee's Knees Superior Pack",
  },
  {
    name: "Crystalice Targe",
    type: "Shield",
    tier: 11,
    unlockPrerequisite: "Snow Day Mega Pack",
  },
  { name: "Abyssal Artifact", type: "Shield", tier: 12 },
  {
    name: "Titan Shield",
    type: "Shield",
    tier: 12,
    unlockPrerequisite: "Shop Titans Mega Pack",
  },
  {
    name: "Opulent Buckler",
    type: "Shield",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Bastion of Dawn",
    type: "Shield",
    tier: 12,
    unlockPrerequisite: "2023 Superior Pack",
  },
  {
    name: "Elongo Shield",
    type: "Shield",
    tier: 12,
    unlockPrerequisite: "Ancient Warrior Mega Pack",
  },
  { name: "Chloroshield", type: "Shield", tier: 13 },
  {
    name: "Mundra's Aegis",
    type: "Shield",
    tier: 13,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Adventurer Cape",
    type: "Cloak",
    tier: 3,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Administrator Cloak",
    type: "Cloak",
    tier: 4,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Druid Cloak",
    type: "Cloak",
    tier: 5,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Imperial Cape",
    type: "Cloak",
    tier: 6,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Vampire Wings",
    type: "Cloak",
    tier: 6,
    unlockPrerequisite: "Pumpkin Superior Pack",
  },
  {
    name: "Elven Cloak",
    type: "Cloak",
    tier: 7,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Beast King's Cloak",
    type: "Cloak",
    tier: 8,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Dragonlord Crest",
    type: "Cloak",
    tier: 9,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Tyrant Cloak",
    type: "Cloak",
    tier: 9,
    unlockPrerequisite: "Castle Superior Pack",
  },
  {
    name: "Archbishop Mantle",
    type: "Cloak",
    tier: 10,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Voidcloth From Beyond",
    type: "Cloak",
    tier: 11,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Opulent Cloak",
    type: "Cloak",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Woven Lilycloak",
    type: "Cloak",
    tier: 11,
    unlockPrerequisite: "Swamp Superior Pack",
  },
  {
    name: "Herald's Mantle",
    type: "Cloak",
    tier: 12,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Sakura Cloak",
    type: "Cloak",
    tier: 12,
    unlockPrerequisite: "Cherry Blossom Superior Pack",
  },
  {
    name: "Fairy Wings",
    type: "Cloak",
    tier: 12,
    unlockPrerequisite: "Junimay Superior Pack",
  },
  {
    name: "Cloak Everflowing",
    type: "Cloak",
    tier: 13,
    unlockPrerequisite: "The Summoner Pack",
  },
  { name: "Iron Ring", type: "Ring", tier: 1, unlockPrerequisite: "Jeweler" },
  { name: "Alloy Loop", type: "Ring", tier: 2 },
  { name: "Ruby Ring", type: "Ring", tier: 3 },
  {
    name: "Emerald Ring",
    type: "Ring",
    tier: 3,
    unlockPrerequisite: "Frozen Chest",
  },
  { name: "Silver Band", type: "Ring", tier: 4 },
  {
    name: "Ring of Passion",
    type: "Ring",
    tier: 4,
    unlockPrerequisite: "Valentine's Day Pack",
  },
  { name: "Noble Ring", type: "Ring", tier: 5 },
  {
    name: "Ring of Rhythm",
    type: "Ring",
    tier: 5,
    unlockPrerequisite: "Cinco De Mayo Mega Pack",
  },
  {
    name: "Claud's Will",
    type: "Ring",
    tier: 5,
    unlockPrerequisite: "Immortal Mega Pack",
  },
  { name: "Knight Signet", type: "Ring", tier: 6 },
  {
    name: "Ring of Liberty",
    type: "Ring",
    tier: 6,
    unlockPrerequisite: "Liberty Mega Pack",
  },
  {
    name: "Qian Loop",
    type: "Ring",
    tier: 6,
    unlockPrerequisite: "Lunar New Year Mega Pack",
  },
  { name: "Batrachite Stone", type: "Ring", tier: 7 },
  {
    name: "Soulstone Ring",
    type: "Ring",
    tier: 7,
    unlockPrerequisite: "Ancient Chest",
  },
  {
    name: "Ring of the Chosen",
    type: "Ring",
    tier: 7,
    unlockPrerequisite: "Hero Pack",
  },
  { name: "Brimstone Coil", type: "Ring", tier: 8 },
  {
    name: "Ring of Vampire Kin",
    type: "Ring",
    tier: 8,
    unlockPrerequisite: "Content Pass: Halloween 2022",
  },
  { name: "Fairfolk Band", type: "Ring", tier: 9 },
  {
    name: "Dawnflower Ring",
    type: "Ring",
    tier: 9,
    unlockPrerequisite: "Spring Festivities Pack",
  },
  {
    name: "Valedictorian Ring",
    type: "Ring",
    tier: 9,
    unlockPrerequisite: "Back to School Mega Pack",
  },
  {
    name: "Luxurious Signet",
    type: "Ring",
    tier: 9,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Borealis", type: "Ring", tier: 10 },
  {
    name: "Northwind Gem",
    type: "Ring",
    tier: 10,
    unlockPrerequisite: "Sunken Chest",
  },
  {
    name: "Blizzard Ring",
    type: "Ring",
    tier: 10,
    unlockPrerequisite: "Winter Superior Offer",
  },
  {
    name: "Bunbun Band",
    type: "Ring",
    tier: 10,
    unlockPrerequisite: "Easter Galore Mega Pack",
  },
  { name: "Rubicon Prison", type: "Ring", tier: 11 },
  {
    name: "Crunchy Bracelet",
    type: "Ring",
    tier: 11,
    unlockPrerequisite: "Super Sweet Mega Pack",
  },
  {
    name: "Ring of New Beginnings",
    type: "Ring",
    tier: 11,
    unlockPrerequisite: "New Year Superior Pack",
  },
  { name: "Pearlescent Perfection", type: "Ring", tier: 12 },
  {
    name: "Crystalice Loop",
    type: "Ring",
    tier: 12,
    unlockPrerequisite: "Polar Superior Pack",
  },
  {
    name: "Ogun's Onyx Ring",
    type: "Ring",
    tier: 12,
    unlockPrerequisite: "Ancient Warrior Superior Pack",
  },
  {
    name: "Maple Ration Mini",
    type: "Ring",
    tier: 12,
    unlockPrerequisite: "Sugar Shack Mega Pack",
  },
  {
    name: "Opulent Signet",
    type: "Ring",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Mark of Ouroboros",
    type: "Ring",
    tier: 13,
    unlockPrerequisite: "Priestess",
  },
  { name: "Memento", type: "Amulet", tier: 1 },
  { name: "Jade Pendant", type: "Amulet", tier: 2 },
  { name: "Iron Bond", type: "Amulet", tier: 3 },
  {
    name: "Mundra's Amulet",
    type: "Amulet",
    tier: 3,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  { name: "Sun Pendant", type: "Amulet", tier: 4 },
  {
    name: "Eclipse Amulet",
    type: "Amulet",
    tier: 4,
    unlockPrerequisite: "Frozen Chest",
  },
  {
    name: "Medal of Honor",
    type: "Amulet",
    tier: 4,
    unlockPrerequisite: "4th of July Pack",
  },
  { name: "Noble Chain", type: "Amulet", tier: 5 },
  {
    name: "Lucky Medallion",
    type: "Amulet",
    tier: 5,
    unlockPrerequisite: "St. Patrick's Day Pack",
  },
  {
    name: "Luxurious Charm",
    type: "Amulet",
    tier: 5,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Holy Symbol", type: "Amulet", tier: 6 },
  {
    name: "Convenient Pendant",
    type: "Amulet",
    tier: 6,
    unlockPrerequisite: "Oktoberfest Mega Pack",
  },
  {
    name: "Trinket of the Fifth",
    type: "Amulet",
    tier: 6,
    unlockPrerequisite: "Cinco de Mayo 3 Mega Pack",
  },
  { name: "Titanium Torc", type: "Amulet", tier: 7 },
  {
    name: "Magical Timepiece",
    type: "Amulet",
    tier: 7,
    unlockPrerequisite: "Back to School Pack",
  },
  { name: "Magatama Necklace", type: "Amulet", tier: 8 },
  {
    name: "Dragonsoul Pendant",
    type: "Amulet",
    tier: 8,
    unlockPrerequisite: "Dragon Siblings Mega Pack",
  },
  {
    name: "Archivist Glasses",
    type: "Amulet",
    tier: 8,
    unlockPrerequisite: "Collection Book",
  },
  { name: "Stygian Phylactery", type: "Amulet", tier: 9 },
  {
    name: "Ursa Totem",
    type: "Amulet",
    tier: 9,
    unlockPrerequisite: "Champion Clash Mega Pack",
  },
  {
    name: "P.E.T. Portable",
    type: "Amulet",
    tier: 9,
    unlockPrerequisite: "Content Pass: Spacefarer",
  },
  { name: "Alimyriad", type: "Amulet", tier: 10 },
  {
    name: "Freyja's Talisman",
    type: "Amulet",
    tier: 10,
    unlockPrerequisite: "Mystic Superior Offer",
  },
  {
    name: "VIP Talisman",
    type: "Amulet",
    tier: 10,
    unlockPrerequisite: "Fortune Superior Offer",
  },
  { name: "Brísingamen", type: "Amulet", tier: 11 },
  {
    name: "Monsoon Heart",
    type: "Amulet",
    tier: 11,
    unlockPrerequisite: "Bleak Chest",
  },
  {
    name: "Forlorn Acorn",
    type: "Amulet",
    tier: 11,
    unlockPrerequisite: "Troublin Superior Pack",
  },
  {
    name: "Gyatso's Amulet",
    type: "Amulet",
    tier: 11,
    unlockPrerequisite: "Fire & Air Mega Pack",
  },
  {
    name: "Fellgrove Talisman",
    type: "Amulet",
    tier: 11,
    unlockPrerequisite: "Fellgrove Superior Pack",
  },
  { name: "Titania's Keepsake", type: "Amulet", tier: 12 },
  {
    name: "Opulent Carcanet",
    type: "Amulet",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Gamepad Mini",
    type: "Amulet",
    tier: 12,
    unlockPrerequisite: "Arcade Superior Pack",
  },
  {
    name: "Eternal Hourglass",
    type: "Amulet",
    tier: 12,
    unlockPrerequisite: "Chronos Ruins Mega Pack",
  },
  {
    name: "Fairy Wreath",
    type: "Amulet",
    tier: 12,
    unlockPrerequisite: "Junimay Superior Pack",
  },
  { name: "Titania's Timepiece", type: "Amulet", tier: 13 },
  {
    name: "Troublin",
    type: "Familiar",
    tier: 3,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Yeti",
    type: "Familiar",
    tier: 4,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Toadwitch",
    type: "Familiar",
    tier: 5,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Mushgoon",
    type: "Familiar",
    tier: 6,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Anubis",
    type: "Familiar",
    tier: 7,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Cyclops",
    type: "Familiar",
    tier: 8,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Tyrant",
    type: "Familiar",
    tier: 9,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Mermaid",
    type: "Familiar",
    tier: 10,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Harpy",
    type: "Familiar",
    tier: 11,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Opulent Golem",
    type: "Familiar",
    tier: 11,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Crushtacean",
    type: "Familiar",
    tier: 12,
    unlockPrerequisite: "The Summoner Pack",
  },
  {
    name: "Voidling",
    type: "Familiar",
    tier: 13,
    unlockPrerequisite: "The Summoner Pack",
  },
  { name: "Bacon and Eggs", type: "Meal", tier: 3, unlockPrerequisite: "Cook" },
  { name: "Gua Bao", type: "Meal", tier: 4 },
  {
    name: "CosmOs Cereals",
    type: "Meal",
    tier: 4,
    unlockPrerequisite: "Content Pass: Spacefarer",
  },
  { name: "Poutine", type: "Meal", tier: 5 },
  {
    name: "Sugar Shack Special",
    type: "Meal",
    tier: 5,
    unlockPrerequisite: "Sugar Shack Mega Pack",
  },
  { name: "Cheeseburger", type: "Meal", tier: 6 },
  {
    name: "Margherita Pizza",
    type: "Meal",
    tier: 6,
    unlockPrerequisite: "Pizza Party Pack",
  },
  {
    name: "Power-Up Pie",
    type: "Meal",
    tier: 6,
    unlockPrerequisite: "Arcade Mega Pack",
  },
  { name: "Ahi Poke Bowl", type: "Meal", tier: 7 },
  {
    name: "Creamy Scallops",
    type: "Meal",
    tier: 7,
    unlockPrerequisite: "New Year 2023 Mega Pack",
  },
  { name: "Sushi", type: "Meal", tier: 8 },
  { name: "Super Spicy Curry", type: "Meal", tier: 9 },
  { name: "Veggie Kebabs", type: "Meal", tier: 10 },
  { name: "Deluxe Ramen", type: "Meal", tier: 11 },
  {
    name: "Steamed Sea Bass",
    type: "Meal",
    tier: 11,
    unlockPrerequisite: "Content Pass: Year of the Rabbit",
  },
  { name: "Huli-Huli Chicken", type: "Meal", tier: 12 },
  {
    name: "Opulent Tamales",
    type: "Meal",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Pot of Paella", type: "Meal", tier: 13 },
  {
    name: "Cookie Plate",
    type: "Dessert",
    tier: 3,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Shaved Ice",
    type: "Dessert",
    tier: 4,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Taiyaki",
    type: "Dessert",
    tier: 5,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Cheesecake",
    type: "Dessert",
    tier: 6,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Chocolate Box",
    type: "Dessert",
    tier: 6,
    unlockPrerequisite: "Valentine 2023 Superior Pack",
  },
  {
    name: "Macaron Set",
    type: "Dessert",
    tier: 7,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Strawberry Mochi",
    type: "Dessert",
    tier: 8,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Matcha Swiss Roll",
    type: "Dessert",
    tier: 9,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Pineapple Cake",
    type: "Dessert",
    tier: 10,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Tuxedo Cake",
    type: "Dessert",
    tier: 11,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Halo-Halo",
    type: "Dessert",
    tier: 12,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Coconut Cream Cake",
    type: "Dessert",
    tier: 12,
    unlockPrerequisite: "Reinhold's Secret Offer",
  },
  {
    name: "Opulent Churros",
    type: "Dessert",
    tier: 12,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Glazed Mirror Cake",
    type: "Dessert",
    tier: 12,
    unlockPrerequisite: "2023 Superior Pack",
  },
  {
    name: "Ultimate Fruit Salad",
    type: "Dessert",
    tier: 13,
    unlockPrerequisite: "The Baker Pack",
  },
  {
    name: "Chipped Runestone",
    type: "Runestone",
    tier: 4,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Flawed Runestone",
    type: "Runestone",
    tier: 7,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Chiseled Runestone",
    type: "Runestone",
    tier: 9,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Perfect Runestone",
    type: "Runestone",
    tier: 12,
    unlockPrerequisite: "Wise Scholar Pack",
  },
  {
    name: "Lesser Moonstone",
    type: "Moonstone",
    tier: 4,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Superior Moonstone",
    type: "Moonstone",
    tier: 7,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Greater Moonstone",
    type: "Moonstone",
    tier: 10,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Perfect Moonstone",
    type: "Moonstone",
    tier: 12,
    unlockPrerequisite: "The Moon Dragon Pack",
  },
  {
    name: "Ember Element",
    type: "Enchantment",
    tier: 4,
    unlockPrerequisite: "Wizard",
  },
  { name: "Flame Element", type: "Enchantment", tier: 7 },
  { name: "Blaze Element", type: "Enchantment", tier: 9 },
  { name: "Inferno Element", type: "Enchantment", tier: 12 },
  {
    name: "Bubble Element",
    type: "Enchantment",
    tier: 4,
    unlockPrerequisite: "Wizard",
  },
  { name: "Tide Element", type: "Enchantment", tier: 7 },
  { name: "Flood Element", type: "Enchantment", tier: 9 },
  { name: "Torrent Element", type: "Enchantment", tier: 12 },
  { name: "Breeze Element", type: "Enchantment", tier: 4 },
  { name: "Gale Element", type: "Enchantment", tier: 7 },
  { name: "Tempest Element", type: "Enchantment", tier: 9 },
  { name: "Hurricane Element", type: "Enchantment", tier: 12 },
  { name: "Nature Element", type: "Enchantment", tier: 4 },
  { name: "Wild Element", type: "Enchantment", tier: 7 },
  { name: "Primal Element", type: "Enchantment", tier: 9 },
  { name: "Primeval Element", type: "Enchantment", tier: 12 },
  { name: "Light Element", type: "Enchantment", tier: 4 },
  { name: "Holy Element", type: "Enchantment", tier: 7 },
  { name: "Sacred Element", type: "Enchantment", tier: 9 },
  { name: "Divine Element", type: "Enchantment", tier: 12 },
  { name: "Corrupted Element", type: "Enchantment", tier: 4 },
  { name: "Unholy Element", type: "Enchantment", tier: 7 },
  { name: "Nightmare Element", type: "Enchantment", tier: 9 },
  { name: "Abyssal Element", type: "Enchantment", tier: 12 },
  {
    name: "Luxurious Element",
    type: "Enchantment",
    tier: 5,
    unlockPrerequisite: "Luxurious Chest",
  },
  {
    name: "Opulent Element",
    type: "Enchantment",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  {
    name: "Ram Spirit",
    type: "Enchantment",
    tier: 4,
    unlockPrerequisite: "Priestess",
  },
  { name: "Wolf Spirit", type: "Enchantment", tier: 4 },
  { name: "Ox Spirit", type: "Enchantment", tier: 4 },
  { name: "Eagle Spirit", type: "Enchantment", tier: 4 },
  { name: "Viper Spirit", type: "Enchantment", tier: 4 },
  { name: "Cat Spirit", type: "Enchantment", tier: 4 },
  {
    name: "Bunny Spirit",
    type: "Enchantment",
    tier: 4,
    unlockPrerequisite: "Content Pass: Year of the Rabbit",
  },
  {
    name: "Xolotl Spirit",
    type: "Enchantment",
    tier: 5,
    unlockPrerequisite: "Luxurious Chest",
  },
  { name: "Rhino Spirit", type: "Enchantment", tier: 7 },
  { name: "Owl Spirit", type: "Enchantment", tier: 7 },
  { name: "Armadillo Spirit", type: "Enchantment", tier: 7 },
  { name: "Lizard Spirit", type: "Enchantment", tier: 7 },
  { name: "Horse Spirit", type: "Enchantment", tier: 7 },
  { name: "Hippo Spirit", type: "Enchantment", tier: 7 },
  { name: "Shark Spirit", type: "Enchantment", tier: 9 },
  { name: "Walrus Spirit", type: "Enchantment", tier: 9 },
  { name: "Lion Spirit", type: "Enchantment", tier: 9 },
  { name: "Bear Spirit", type: "Enchantment", tier: 9 },
  { name: "Mammoth Spirit", type: "Enchantment", tier: 9 },
  { name: "Dinosaur Spirit", type: "Enchantment", tier: 9 },
  {
    name: "Tiger Spirit",
    type: "Enchantment",
    tier: 9,
    unlockPrerequisite: "Content Pass: Year of the Tiger",
  },
  {
    name: "Quetzalcoatl Spirit",
    type: "Enchantment",
    tier: 10,
    unlockPrerequisite: "Opulent Chest",
  },
  { name: "Phoenix Spirit", type: "Enchantment", tier: 12 },
  { name: "Hydra Spirit", type: "Enchantment", tier: 12 },
  { name: "Tarrasque Spirit", type: "Enchantment", tier: 12 },
  { name: "Carbuncle Spirit", type: "Enchantment", tier: 12 },
  { name: "Chimera Spirit", type: "Enchantment", tier: 12 },
  { name: "Kraken Spirit", type: "Enchantment", tier: 12 },
  {
    name: "Christmas Spirit",
    type: "Enchantment",
    tier: 12,
    unlockPrerequisite: "Holiday 2022 Superior Pack",
  },
]);
