db.blueprints.insertMany([
  { name: "Squire Sword", type: "Sword", tier: 1 },
  { name: "Arming Sword", type: "Sword", tier: 2 },
  { name: "Gladius", type: "Sword", tier: 3 },
  { name: "Arboreal Blade", type: "Sword", tier: 3 },
  { name: "Zweihander", type: "Sword", tier: 3 },
  { name: "Cutlass", type: "Sword", tier: 4 },
  { name: "Espada", type: "Sword", tier: 5 },
  { name: "Hero's Sword", type: "Sword", tier: 5 },
  { name: "Chocolicious Blade", type: "Sword", tier: 5 },
  { name: "Katana", type: "Sword", tier: 6 },
  { name: "Serrated Cinquedea", type: "Sword", tier: 6 },
  { name: "Regal Blade", type: "Sword", tier: 7 },
  { name: "Chronos Runeblade", type: "Sword", tier: 7 },
  { name: "Celesteel Blade", type: "Sword", tier: 8 },
  { name: "Damocles", type: "Sword", tier: 8 },
  { name: "Luxurious Macuahuitl", type: "Sword", tier: 8 },
  { name: "Mythril Edge", type: "Sword", tier: 9 },
  { name: "Seafarer Blade", type: "Sword", tier: 9 },
  { name: "Gentleman Blade", type: "Sword", tier: 9 },
  { name: "Oversized Cleaver", type: "Sword", tier: 10 },
  { name: "Caladbolg", type: "Sword", tier: 10 },
  { name: "Dragon Dao", type: "Sword", tier: 10 },
  { name: "Tiger Blade", type: "Sword", tier: 10 },
  { name: "Vorpal Sword", type: "Sword", tier: 11 },
  { name: "Elegant Rapier", type: "Sword", tier: 11 },
  { name: "Tsukuyomi", type: "Sword", tier: 11 },
  { name: "Excalibur", type: "Sword", tier: 12 },
  { name: "Titan Sword", type: "Sword", tier: 12 },
  { name: "Opulent Brand", type: "Sword", tier: 12 },
  { name: "Épée d'Artagnan", type: "Sword", tier: 12 },
  { name: "Thorn of Scorn", type: "Sword", tier: 12 },
  { name: "Djinn Pyre", type: "Sword", tier: 13 },
  { name: "Plasma Saber", type: "Sword", tier: 13 },
  { name: "Wood Axe", type: "Axe", tier: 1 },
  { name: "Hatchet", type: "Axe", tier: 2 },
  { name: "Iron Chopper", type: "Axe", tier: 3 },
  { name: "Explorer's Axe", type: "Axe", tier: 3 },
  { name: "Bardiche", type: "Axe", tier: 4 },
  { name: "Molten Voulge", type: "Axe", tier: 4 },
  { name: "Dismantler's Pickaxe", type: "Axe", tier: 4 },
  { name: "Tomahawk", type: "Axe", tier: 5 },
  { name: "Companion Axe", type: "Axe", tier: 5 },
  { name: "Cold Iron Axe", type: "Axe", tier: 5 },
  { name: "Battleaxe", type: "Axe", tier: 6 },
  { name: "Raptor Reaper", type: "Axe", tier: 6 },
  { name: "Dwarven Greataxe", type: "Axe", tier: 7 },
  { name: "Stonesplitter", type: "Axe", tier: 7 },
  { name: "Raider Axe", type: "Axe", tier: 8 },
  { name: "Qian Chopper", type: "Axe", tier: 8 },
  { name: "Executioner", type: "Axe", tier: 9 },
  { name: "Purgatory", type: "Axe", tier: 9 },
  { name: "Axe of The Fifth", type: "Axe", tier: 9 },
  { name: "Eclipsis", type: "Axe", tier: 10 },
  { name: "Terra Tyrannis", type: "Axe", tier: 10 },
  { name: "Opulent Grandaxe", type: "Axe", tier: 10 },
  { name: "Kodiak Kleaver", type: "Axe", tier: 10 },
  { name: "Manticore Slayer", type: "Axe", tier: 11 },
  { name: "Beeswaxe", type: "Axe", tier: 11 },
  { name: "Shroom Doom", type: "Axe", tier: 11 },
  { name: "Jötunnbane", type: "Axe", tier: 11 },
  { name: "Crescent of Conquest", type: "Axe", tier: 12 },
  { name: "Onyx King Axe", type: "Axe", tier: 12 },
  { name: "Lover's Quarrel", type: "Axe", tier: 12 },
  { name: "Apex Goraxe", type: "Axe", tier: 12 },
  { name: "Edge Eternal", type: "Axe", tier: 13 },
  { name: "Shiv", type: "Dagger", tier: 1 },
  { name: "Ice Pick", type: "Dagger", tier: 1 },
  { name: "Swift Blade", type: "Dagger", tier: 2 },
  { name: "Kunai", type: "Dagger", tier: 2 },
  { name: "Stealth Knife", type: "Dagger", tier: 3 },
  { name: "Balisong", type: "Dagger", tier: 4 },
  { name: "Erudite Vector", type: "Dagger", tier: 4 },
  { name: "Ritual Dagger", type: "Dagger", tier: 5 },
  { name: "Sokka's Boomerang", type: "Dagger", tier: 5 },
  { name: "Assassin Tanto", type: "Dagger", tier: 5 },
  { name: "Kingsguard", type: "Dagger", tier: 6 },
  { name: "Cloudwalker Chakram", type: "Dagger", tier: 6 },
  { name: "Fishmonger", type: "Dagger", tier: 7 },
  { name: "Juniper's Trowel", type: "Dagger", tier: 7 },
  { name: "Troll Tooth", type: "Dagger", tier: 8 },
  { name: "Levia Fang", type: "Dagger", tier: 8 },
  { name: "Misericordia", type: "Dagger", tier: 9 },
  { name: "Sultan Dagger", type: "Dagger", tier: 9 },
  { name: "Luxurious Poignard", type: "Dagger", tier: 9 },
  { name: "Ceremonial Katar", type: "Dagger", tier: 10 },
  { name: "Nightmare Fellblade", type: "Dagger", tier: 10 },
  { name: "Swan's Edge", type: "Dagger", tier: 10 },
  { name: "Lucky Strike", type: "Dagger", tier: 10 },
  { name: "Heartseeker", type: "Dagger", tier: 11 },
  { name: "Last Breath", type: "Dagger", tier: 11 },
  { name: "Nightwing Bolt", type: "Dagger", tier: 11 },
  { name: "Kyoshi Warrior Fan", type: "Dagger", tier: 11 },
  { name: "Wiccan Dagger", type: "Dagger", tier: 11 },
  { name: "Sixth Sin", type: "Dagger", tier: 12 },
  { name: "Opulent Tecpatl", type: "Dagger", tier: 12 },
  { name: "Celesteel Knuckles", type: "Dagger", tier: 12 },
  { name: "Empress War Fan", type: "Dagger", tier: 12 },
  { name: "Nocturne", type: "Dagger", tier: 13 },
  { name: "Cudgel", type: "Mace", tier: 1 },
  { name: "Spiked Cudgel", type: "Mace", tier: 2 },
  { name: "Darkwood Branch", type: "Mace", tier: 2 },
  { name: "Warhammer", type: "Mace", tier: 3 },
  { name: "Liberty Mace", type: "Mace", tier: 3 },
  { name: "Morning Star", type: "Mace", tier: 4 },
  { name: "Inflatable Maul", type: "Mace", tier: 4 },
  { name: "Flanged Mace", type: "Mace", tier: 5 },
  { name: "First Morning Star", type: "Mace", tier: 5 },
  { name: "Skull Crusher", type: "Mace", tier: 6 },
  { name: "Troublin Bludgeon", type: "Mace", tier: 6 },
  { name: "Evening Star", type: "Mace", tier: 7 },
  { name: "Meteor Hammer", type: "Mace", tier: 7 },
  { name: "Button Masher", type: "Mace", tier: 7 },
  { name: "Powder Keg", type: "Mace", tier: 8 },
  { name: "Whack-O'-Lantern", type: "Mace", tier: 8 },
  { name: "Peppermint Mallet", type: "Mace", tier: 8 },
  { name: "Tenderizer", type: "Mace", tier: 9 },
  { name: "Wallace Mallet", type: "Mace", tier: 9 },
  { name: "Striped Star", type: "Mace", tier: 9 },
  { name: "Nautilus", type: "Mace", tier: 10 },
  { name: "Opulent Maul", type: "Mace", tier: 10 },
  { name: "Mundra's Masher", type: "Mace", tier: 10 },
  { name: "Thorium Hammer", type: "Mace", tier: 11 },
  { name: "Sunglow Impact", type: "Mace", tier: 11 },
  { name: "Gaia Maul", type: "Mace", tier: 11 },
  { name: "Sokka's Club", type: "Mace", tier: 11 },
  { name: "Mjölnir", type: "Mace", tier: 12 },
  { name: "Eggshell Smasher", type: "Mace", tier: 12 },
  { name: "Merry Christmace", type: "Mace", tier: 12 },
  { name: "Crag Guardian", type: "Mace", tier: 13 },
  { name: "Smash Hit", type: "Mace", tier: 13 },
  { name: "Javelin", type: "Spear", tier: 1 },
  { name: "Hunting Spear", type: "Spear", tier: 2 },
  { name: "Bladed Spear", type: "Spear", tier: 3 },
  { name: "Sturdy Pitchfork", type: "Spear", tier: 3 },
  { name: "Ranseur", type: "Spear", tier: 4 },
  { name: "Trishula", type: "Spear", tier: 5 },
  { name: "Bunbun Lance", type: "Spear", tier: 5 },
  { name: "Warlord Halberd", type: "Spear", tier: 5 },
  { name: "Spetum", type: "Spear", tier: 6 },
  { name: "Triton Lance", type: "Spear", tier: 6 },
  { name: "Cu Chulainn's Lance", type: "Spear", tier: 6 },
  { name: "Royal Halberd", type: "Spear", tier: 7 },
  { name: "Twicicle Javelin", type: "Spear", tier: 7 },
  { name: "Warrior Assegai", type: "Spear", tier: 7 },
  { name: "Champion Lance", type: "Spear", tier: 8 },
  { name: "Sunset Yari", type: "Spear", tier: 8 },
  { name: "Wyvern Glaive", type: "Spear", tier: 9 },
  { name: "Hoartooth Lance", type: "Spear", tier: 9 },
  { name: "Luxurious Spear", type: "Spear", tier: 9 },
  { name: "Stellaria", type: "Spear", tier: 10 },
  { name: "Longinus", type: "Spear", tier: 10 },
  { name: "Birdbane Halberd", type: "Spear", tier: 10 },
  { name: "Titania's Gift", type: "Spear", tier: 11 },
  { name: "Jester Jouster", type: "Spear", tier: 11 },
  { name: "Holy Night Lance", type: "Spear", tier: 11 },
  { name: "Heaven's Wrath", type: "Spear", tier: 12 },
  { name: "Propeller-Pike", type: "Spear", tier: 12 },
  { name: "Pokey Parasol", type: "Spear", tier: 12 },
  { name: "Opulent Halberd", type: "Spear", tier: 12 },
  { name: "Blackened Bardiche", type: "Spear", tier: 13 },
  { name: "Riptide", type: "Spear", tier: 13 },
  { name: "Training Bow", type: "Bow", tier: 1 },
  { name: "Tailwind", type: "Bow", tier: 1 },
  { name: "Elmwood Bow", type: "Bow", tier: 2 },
  { name: "Reflex Bow", type: "Bow", tier: 3 },
  { name: "Grand Harp", type: "Bow", tier: 3 },
  { name: "Compound Bow", type: "Bow", tier: 4 },
  { name: "Mundra's Hornbow", type: "Bow", tier: 4 },
  { name: "Deadeye", type: "Bow", tier: 5 },
  { name: "Hallowed Willow", type: "Bow", tier: 5 },
  { name: "Raptoria", type: "Bow", tier: 6 },
  { name: "Quetzal Wing", type: "Bow", tier: 6 },
  { name: "L'Arabesque", type: "Bow", tier: 7 },
  { name: "Hotshot Bowgun", type: "Bow", tier: 7 },
  { name: "Yumi", type: "Bow", tier: 8 },
  { name: "Cupid Bow", type: "Bow", tier: 8 },
  { name: "Bramblebane", type: "Bow", tier: 9 },
  { name: "Maplewood Gale", type: "Bow", tier: 9 },
  { name: "Gemini Strike", type: "Bow", tier: 10 },
  { name: "Jolly Ranger", type: "Bow", tier: 10 },
  { name: "Stormrend", type: "Bow", tier: 11 },
  { name: "Opulent Longbow", type: "Bow", tier: 11 },
  { name: "Pinata Hunter", type: "Bow", tier: 11 },
  { name: "Rising Star", type: "Bow", tier: 11 },
  { name: "Boughwrought Bow", type: "Bow", tier: 11 },
  { name: "Olympus", type: "Bow", tier: 12 },
  { name: "Power Flipper", type: "Bow", tier: 12 },
  { name: "Elite Pathfinder", type: "Bow", tier: 12 },
  { name: "Grand Monarque", type: "Bow", tier: 13 },
  { name: "Earthstrung Wings", type: "Bow", tier: 13 },
  { name: "Jindai Zakura", type: "Bow", tier: 13 },
  { name: "Carved Branch", type: "Staff", tier: 1 },
  { name: "Sturdy Cane", type: "Staff", tier: 2 },
  { name: "Oak Staff", type: "Staff", tier: 3 },
  { name: "Owl Perch", type: "Staff", tier: 3 },
  { name: "Luxurious Stick", type: "Staff", tier: 3 },
  { name: "Bo Staff", type: "Staff", tier: 4 },
  { name: "Apprentice Staff", type: "Staff", tier: 4 },
  { name: "Jade Scepter", type: "Staff", tier: 5 },
  { name: "Amber Staff", type: "Staff", tier: 5 },
  { name: "Wiccan Broomstick", type: "Staff", tier: 5 },
  { name: "Wizard Staff", type: "Staff", tier: 6 },
  { name: "Staff of Seasons", type: "Staff", tier: 6 },
  { name: "Celestial Staff", type: "Staff", tier: 7 },
  { name: "Mundra's Scepter", type: "Staff", tier: 7 },
  { name: "Imperial Aquila", type: "Staff", tier: 8 },
  { name: "Phoenix Staff", type: "Staff", tier: 8 },
  { name: "Fluted Chime", type: "Staff", tier: 8 },
  { name: "Transcendence", type: "Staff", tier: 9 },
  { name: "Tidebringer", type: "Staff", tier: 9 },
  { name: "Zesty Scepter", type: "Staff", tier: 9 },
  { name: "Seraphim", type: "Staff", tier: 10 },
  { name: "Staff of Merriment", type: "Staff", tier: 10 },
  { name: "Penumbra", type: "Staff", tier: 11 },
  { name: "Ice Queen's Scepter", type: "Staff", tier: 11 },
  { name: "Heartcaptor's Staff", type: "Staff", tier: 11 },
  { name: "Scepter of Xolimnul", type: "Staff", tier: 12 },
  { name: "Opulent Staff", type: "Staff", tier: 12 },
  { name: "Soulbinder Staff", type: "Staff", tier: 12 },
  { name: "Pharaoh's Ankh", type: "Staff", tier: 12 },
  { name: "Cloud Nine", type: "Staff", tier: 13 },
  { name: "Gravity Controller", type: "Staff", tier: 13 },
  { name: "Baton", type: "Wand", tier: 1 },
  { name: "Elvenwood Wand", type: "Wand", tier: 2 },
  { name: "Hexer's Wand", type: "Wand", tier: 3 },
  { name: "Steel Rod", type: "Wand", tier: 4 },
  { name: "Star Rod", type: "Wand", tier: 5 },
  { name: "Peppermint Cane", type: "Wand", tier: 5 },
  { name: "Sylvanel", type: "Wand", tier: 6 },
  { name: "Chōchin Gohei", type: "Wand", tier: 6 },
  { name: "Ruby Wand", type: "Wand", tier: 7 },
  { name: "Owl Wing Wand", type: "Wand", tier: 7 },
  { name: "Wand of Midas", type: "Wand", tier: 8 },
  { name: "Evergreen Wand", type: "Wand", tier: 9 },
  { name: "Equinox Rod", type: "Wand", tier: 9 },
  { name: "Astral Conductor", type: "Wand", tier: 10 },
  { name: "Grimar's Grand Wand", type: "Wand", tier: 10 },
  { name: "Draconic Eyestalk", type: "Wand", tier: 11 },
  { name: "Opulent Wand", type: "Wand", tier: 11 },
  { name: "Moonlight Wand", type: "Wand", tier: 11 },
  { name: "Herald of the End", type: "Wand", tier: 12 },
  { name: "Ivory Queen Rod", type: "Wand", tier: 12 },
  { name: "Fork of Roasting", type: "Wand", tier: 12 },
  { name: "Pyroquartz Rod", type: "Wand", tier: 13 },
  { name: "Light Crossbow", type: "Crossbow", tier: 1 },
  { name: "Hand Crossbow", type: "Crossbow", tier: 2 },
  { name: "Arbalest", type: "Crossbow", tier: 3 },
  { name: "Heavy Crossbow", type: "Crossbow", tier: 4 },
  { name: "Cluckthrower", type: "Crossbow", tier: 4 },
  { name: "Hunter's Crossbow", type: "Crossbow", tier: 5 },
  { name: "Scorpio", type: "Crossbow", tier: 6 },
  { name: "Primitech Slingshot", type: "Crossbow", tier: 6 },
  { name: "Double Crossbow", type: "Crossbow", tier: 7 },
  { name: "Chu-Ko-Nu", type: "Crossbow", tier: 8 },
  { name: "Dra-Ko-Nu", type: "Crossbow", tier: 8 },
  { name: "Triple Crossbow", type: "Crossbow", tier: 9 },
  { name: "Super Repeater", type: "Crossbow", tier: 10 },
  { name: "Nightwing Caster", type: "Crossbow", tier: 10 },
  { name: "Leviathan", type: "Crossbow", tier: 11 },
  { name: "Opulent Crossbow", type: "Crossbow", tier: 11 },
  { name: "Titan Crossbow", type: "Crossbow", tier: 11 },
  { name: "Godslayer Arbalest", type: "Crossbow", tier: 12 },
  { name: "Baross' Backup", type: "Crossbow", tier: 12 },
  { name: "Primarosa", type: "Crossbow", tier: 13 },
  { name: "Pellet Gun", type: "Gun", tier: 1 },
  { name: "Handgun", type: "Gun", tier: 2 },
  { name: "Smoothbore", type: "Gun", tier: 3 },
  { name: "Long Rifle", type: "Gun", tier: 4 },
  { name: "Snowball Launcher", type: "Gun", tier: 4 },
  { name: "Blunderbuss", type: "Gun", tier: 5 },
  { name: "Boomstick", type: "Gun", tier: 6 },
  { name: "Banana Gun", type: "Gun", tier: 6 },
  { name: "Pellet Popper", type: "Gun", tier: 6 },
  { name: "Kenora Mk. IV", type: "Gun", tier: 7 },
  { name: "Prototype Gatling", type: "Gun", tier: 8 },
  { name: "Dragonator", type: "Gun", tier: 9 },
  { name: "Handcask '65", type: "Gun", tier: 9 },
  { name: "The Messenger", type: "Gun", tier: 10 },
  { name: "Oxen Impact", type: "Gun", tier: 10 },
  { name: "Omega Disintegrator", type: "Gun", tier: 11 },
  { name: "Opulent Pistol", type: "Gun", tier: 11 },
  { name: "Dogbone Blaster", type: "Gun", tier: 11 },
  { name: "Blackbeard's Cannon", type: "Gun", tier: 12 },
  { name: "Hotshot Carbine", type: "Gun", tier: 12 },
  { name: "Gift Wrap Rifle", type: "Gun", tier: 12 },
  { name: "Vainglory", type: "Gun", tier: 13 },
  { name: "Sonic Trumpeteer", type: "Gun", tier: 13 },
  { name: "Mintyleaf Herb", type: "Herbal Medicine", tier: 1 },
  { name: "Sweet Grass", type: "Herbal Medicine", tier: 2 },
  { name: "Moon Powder", type: "Herbal Medicine", tier: 3 },
  { name: "Magical Mistletoe", type: "Herbal Medicine", tier: 3 },
  { name: "Healing Salve", type: "Herbal Medicine", tier: 4 },
  { name: "Venerable Oats", type: "Herbal Medicine", tier: 4 },
  { name: "Silver Thistle", type: "Herbal Medicine", tier: 5 },
  { name: "Bountiful Harvest", type: "Herbal Medicine", tier: 5 },
  { name: "Flint Corn Bundle", type: "Herbal Medicine", tier: 5 },
  { name: "Bloodvine", type: "Herbal Medicine", tier: 6 },
  { name: "Fragrant Bouquet", type: "Herbal Medicine", tier: 6 },
  { name: "Lil' Cactus", type: "Herbal Medicine", tier: 6 },
  { name: "Mandragoroot", type: "Herbal Medicine", tier: 7 },
  { name: "Unwilting Rose", type: "Herbal Medicine", tier: 7 },
  { name: "Wolf's Bane", type: "Herbal Medicine", tier: 8 },
  { name: "Mistpeak Bloom", type: "Herbal Medicine", tier: 8 },
  { name: "Yggdrasil Branch", type: "Herbal Medicine", tier: 9 },
  { name: "Luckiest Clover", type: "Herbal Medicine", tier: 9 },
  { name: "Luxurious Panacea", type: "Herbal Medicine", tier: 9 },
  { name: "Wyrmblood Ointment", type: "Herbal Medicine", tier: 10 },
  { name: "Wild Oak Rose", type: "Herbal Medicine", tier: 10 },
  { name: "Florae Daemonica", type: "Herbal Medicine", tier: 11 },
  { name: "Bleakspire Roots", type: "Herbal Medicine", tier: 11 },
  { name: "Seltzer Surprise", type: "Herbal Medicine", tier: 11 },
  { name: "Super Snack Pack", type: "Herbal Medicine", tier: 11 },
  { name: "Philosopher's Stone", type: "Herbal Medicine", tier: 12 },
  { name: "Sakura Infusion", type: "Herbal Medicine", tier: 12 },
  { name: "Opulent Decoction", type: "Herbal Medicine", tier: 12 },
  { name: "Premium Brand Jam", type: "Herbal Medicine", tier: 12 },
  { name: "Voidbloom Roots", type: "Herbal Medicine", tier: 13 },
  { name: "Slide Grease", type: "Herbal Medicine", tier: 13 },
  { name: "Warm Tea", type: "Potion", tier: 1 },
  { name: "Healing Potion", type: "Potion", tier: 2 },
  { name: "Magic Potion", type: "Potion", tier: 3 },
  { name: "Science Project", type: "Potion", tier: 3 },
  { name: "XL Healing Potion", type: "Potion", tier: 4 },
  { name: "Elegant Tea Set", type: "Potion", tier: 4 },
  { name: "XL Magic Potion", type: "Potion", tier: 5 },
  { name: "Titan Potion", type: "Potion", tier: 5 },
  { name: "Old Salt's Brew", type: "Potion", tier: 5 },
  { name: "Phoenix Tonic", type: "Potion", tier: 6 },
  { name: "Zesty Granita", type: "Potion", tier: 6 },
  { name: "Potion of Renewal", type: "Potion", tier: 7 },
  { name: "Bottled Mirth", type: "Potion", tier: 7 },
  { name: "Fizzy Guzzle Bottle", type: "Potion", tier: 7 },
  { name: "Purple Bomb", type: "Potion", tier: 8 },
  { name: "Gourd Elixir", type: "Potion", tier: 8 },
  { name: "Naya's Special", type: "Potion", tier: 8 },
  { name: "Special Sazonado", type: "Potion", tier: 8 },
  { name: "Soulfire Extract", type: "Potion", tier: 9 },
  { name: "Tangy Decoction", type: "Potion", tier: 9 },
  { name: "Oak Essence", type: "Potion", tier: 9 },
  { name: "Gaia Tonic", type: "Potion", tier: 10 },
  { name: "Midnight Oil", type: "Potion", tier: 10 },
  { name: "Opulent Elixir", type: "Potion", tier: 10 },
  { name: "Distilled Nebula", type: "Potion", tier: 11 },
  { name: "Aurora Springwater", type: "Potion", tier: 11 },
  { name: "Nectar Pitcher", type: "Potion", tier: 11 },
  { name: "Ambrosia", type: "Potion", tier: 12 },
  { name: "Mundra's Remedy", type: "Potion", tier: 12 },
  { name: "Quintessence Purity", type: "Potion", tier: 12 },
  { name: "Supreme Sunscreen", type: "Potion", tier: 12 },
  { name: "Maple Holy Grail", type: "Potion", tier: 12 },
  { name: "Conqueror's Blood", type: "Potion", tier: 13 },
  { name: "Satchel of Essentials", type: "Potion", tier: 13 },
  { name: "Scroll of Sparks", type: "Spell", tier: 1 },
  { name: "Scroll of Cleansing", type: "Spell", tier: 1 },
  { name: "Scroll of Armor", type: "Spell", tier: 2 },
  { name: "Scroll of Storms", type: "Spell", tier: 3 },
  { name: "Song of Valor", type: "Spell", tier: 4 },
  { name: "Correspondence", type: "Spell", tier: 4 },
  { name: "Monster Manual", type: "Spell", tier: 5 },
  { name: "Tome of the Night", type: "Spell", tier: 5 },
  { name: "Tome of Knowledge", type: "Spell", tier: 5 },
  { name: "Tome of Secrets", type: "Spell", tier: 6 },
  { name: "Naughty or Nice List", type: "Spell", tier: 6 },
  { name: "Bagua Board", type: "Spell", tier: 7 },
  { name: "Firework Bundle", type: "Spell", tier: 7 },
  { name: "Tale of the Unicorn", type: "Spell", tier: 7 },
  { name: "Tarot Deck", type: "Spell", tier: 8 },
  { name: "Scroll of Fortune", type: "Spell", tier: 8 },
  { name: "Grimoire Aeternum", type: "Spell", tier: 9 },
  { name: "Imperial Decree", type: "Spell", tier: 9 },
  { name: "Luxurious Tablet", type: "Spell", tier: 9 },
  { name: "Ancestral Atlas", type: "Spell", tier: 10 },
  { name: "Prayer Book", type: "Spell", tier: 10 },
  { name: "Curse of the Night", type: "Spell", tier: 10 },
  { name: "Druidic Grimoire", type: "Spell", tier: 10 },
  { name: "Celestial Choir", type: "Spell", tier: 11 },
  { name: "Phoenix Litany", type: "Spell", tier: 11 },
  { name: "Sealed Declaration", type: "Spell", tier: 11 },
  { name: "Tiger Emperor's Edict", type: "Spell", tier: 11 },
  { name: "Tome of All-Knowledge", type: "Spell", tier: 11 },
  { name: "The Bound Beast", type: "Spell", tier: 12 },
  { name: "Pharaoh's Pact", type: "Spell", tier: 12 },
  { name: "Lost Star Chart", type: "Spell", tier: 12 },
  { name: "Love Declaration", type: "Spell", tier: 12 },
  { name: "Opulent Incantation", type: "Spell", tier: 12 },
  { name: "Pandora's Box", type: "Spell", tier: 13 },
  { name: "Sealed Hurricane", type: "Spell", tier: 13 },
  { name: "Breastplate", type: "Heavy Armor", tier: 1 },
  { name: "Iron Mail", type: "Heavy Armor", tier: 2 },
  { name: "Scale Armor", type: "Heavy Armor", tier: 3 },
  { name: "Hauberk", type: "Heavy Armor", tier: 4 },
  { name: "Knight Breastplate", type: "Heavy Armor", tier: 5 },
  { name: "Ceremonial Breastplate", type: "Heavy Armor", tier: 5 },
  { name: "Centurion Armor", type: "Heavy Armor", tier: 5 },
  { name: "Paladin Plate", type: "Heavy Armor", tier: 6 },
  { name: "Thorn Baron Armor", type: "Heavy Armor", tier: 6 },
  { name: "Hive Guard Plate", type: "Heavy Armor", tier: 6 },
  { name: "Samurai Do", type: "Heavy Armor", tier: 7 },
  { name: "Brinewater Do", type: "Heavy Armor", tier: 7 },
  { name: "Kyoshi Warrior Armor", type: "Heavy Armor", tier: 7 },
  { name: "Warlord Plate", type: "Heavy Armor", tier: 7 },
  { name: "General Plate", type: "Heavy Armor", tier: 8 },
  { name: "Landsknecht Plate", type: "Heavy Armor", tier: 8 },
  { name: "Santa's Guard Plate", type: "Heavy Armor", tier: 8 },
  { name: "Berserker Armor", type: "Heavy Armor", tier: 9 },
  { name: "Gaia Enforcer", type: "Heavy Armor", tier: 9 },
  { name: "Star-Spangled Plate", type: "Heavy Armor", tier: 9 },
  { name: "Juggernaut Fortress", type: "Heavy Armor", tier: 10 },
  { name: "Amber Citadel", type: "Heavy Armor", tier: 10 },
  { name: "Opulent Breastplate", type: "Heavy Armor", tier: 10 },
  { name: "Milesian Mail", type: "Heavy Armor", tier: 10 },
  { name: "Celesteel Plate", type: "Heavy Armor", tier: 11 },
  { name: "Canid Plate", type: "Heavy Armor", tier: 11 },
  { name: "Fire Nation Armor", type: "Heavy Armor", tier: 11 },
  { name: "Vermilion Guard Plate", type: "Heavy Armor", tier: 12 },
  { name: "Oni Rōnin Armor", type: "Heavy Armor", tier: 12 },
  { name: "Tyrant Plate Armor", type: "Heavy Armor", tier: 12 },
  { name: "Lost Warrior's Plate", type: "Heavy Armor", tier: 12 },
  { name: "Balefire Armor", type: "Heavy Armor", tier: 13 },
  { name: "Magmacore Plate", type: "Heavy Armor", tier: 13 },
  { name: "Leather Armor", type: "Light Armor", tier: 1 },
  { name: "Gambeson", type: "Light Armor", tier: 2 },
  { name: "Doublet", type: "Light Armor", tier: 3 },
  { name: "Studded Armor", type: "Light Armor", tier: 4 },
  { name: "Blizzard Armor", type: "Light Armor", tier: 4 },
  { name: "Hide Armor", type: "Light Armor", tier: 5 },
  { name: "Mundra's Tabard", type: "Light Armor", tier: 5 },
  { name: "Sky Pirate Outfit", type: "Light Armor", tier: 5 },
  { name: "Savage Garb", type: "Light Armor", tier: 6 },
  { name: "Glade Guard Armor", type: "Light Armor", tier: 6 },
  { name: "Pumpkin Armor", type: "Light Armor", tier: 6 },
  { name: "Ninja Garb", type: "Light Armor", tier: 7 },
  { name: "Nightwing Mantle", type: "Light Armor", tier: 7 },
  { name: "Windrunner Armor", type: "Light Armor", tier: 8 },
  { name: "Sokka's Outfit", type: "Light Armor", tier: 8 },
  { name: "Drakeskin Armor", type: "Light Armor", tier: 9 },
  { name: "Smith Attire", type: "Light Armor", tier: 9 },
  { name: "Corsair Mantle", type: "Light Armor", tier: 10 },
  { name: "Swan's Garment", type: "Light Armor", tier: 10 },
  { name: "Cloudwalker Armor", type: "Light Armor", tier: 10 },
  { name: "Everdusk Lord Attire", type: "Light Armor", tier: 11 },
  { name: "Opulent Armor", type: "Light Armor", tier: 11 },
  { name: "Barkback's Armor", type: "Light Armor", tier: 11 },
  { name: "Cat Burglar Outfit", type: "Light Armor", tier: 11 },
  { name: "Dawn Thief Uniform", type: "Light Armor", tier: 12 },
  { name: "Shroud of the Lost", type: "Light Armor", tier: 12 },
  { name: "Stylish Poncho", type: "Light Armor", tier: 12 },
  { name: "Desperado Outfit", type: "Light Armor", tier: 12 },
  { name: "Wildhunt Leathers", type: "Light Armor", tier: 13 },
  { name: "Shirt", type: "Clothes", tier: 1 },
  { name: "Black Robe", type: "Clothes", tier: 2 },
  { name: "Druid's Robe", type: "Clothes", tier: 3 },
  { name: "Disciple's Robe", type: "Clothes", tier: 4 },
  { name: "Scholar's Tunic", type: "Clothes", tier: 5 },
  { name: "Explorer's Outfit", type: "Clothes", tier: 5 },
  { name: "Tailor Mantle", type: "Clothes", tier: 5 },
  { name: "Witch's Outfit", type: "Clothes", tier: 6 },
  { name: "Vestal Raiments", type: "Clothes", tier: 6 },
  { name: "Wizard Attire", type: "Clothes", tier: 6 },
  { name: "Midnight Apparel", type: "Clothes", tier: 7 },
  { name: "Aang's Robe", type: "Clothes", tier: 7 },
  { name: "Shaman Vestment", type: "Clothes", tier: 8 },
  { name: "Cupid Robes", type: "Clothes", tier: 8 },
  { name: "Luxurious Attire", type: "Clothes", tier: 8 },
  { name: "Astravestimenta", type: "Clothes", tier: 9 },
  { name: "Ostara Vest", type: "Clothes", tier: 9 },
  { name: "Desert Threads", type: "Clothes", tier: 9 },
  { name: "Archmage Raiments", type: "Clothes", tier: 10 },
  { name: "Republic Garments", type: "Clothes", tier: 10 },
  { name: "Djinn Robes", type: "Clothes", tier: 11 },
  { name: "Moonlight Kimono", type: "Clothes", tier: 11 },
  { name: "Tiger Emperor's Robe", type: "Clothes", tier: 11 },
  { name: "Exarch Robes", type: "Clothes", tier: 12 },
  { name: "Soulbinder Regalia", type: "Clothes", tier: 12 },
  { name: "Opulent Vestment", type: "Clothes", tier: 12 },
  { name: "Garb of the Primordial", type: "Clothes", tier: 12 },
  { name: "Ice Queen's Silks", type: "Clothes", tier: 12 },
  { name: "Voidminster Habit", type: "Clothes", tier: 13 },
  { name: "Sturdy Cap", type: "Helmet", tier: 1 },
  { name: "Warrior Helmet", type: "Helmet", tier: 2 },
  { name: "Horned Helm", type: "Helmet", tier: 3 },
  { name: "Raider Helm", type: "Helmet", tier: 4 },
  { name: "Knight Heaume", type: "Helmet", tier: 5 },
  { name: "Brinewater Helm", type: "Helmet", tier: 5 },
  { name: "Eagle Helm", type: "Helmet", tier: 5 },
  { name: "Rex Chomper", type: "Helmet", tier: 5 },
  { name: "Paladin Helm", type: "Helmet", tier: 6 },
  { name: "Kodiak Helmet", type: "Helmet", tier: 6 },
  { name: "Fire Nation Helm", type: "Helmet", tier: 6 },
  { name: "Crown of Tyranny", type: "Helmet", tier: 6 },
  { name: "Samurai Kabuto", type: "Helmet", tier: 7 },
  { name: "Gladiator Helm", type: "Helmet", tier: 7 },
  { name: "Sandcastle Protector", type: "Helmet", tier: 7 },
  { name: "General Heaume", type: "Helmet", tier: 8 },
  { name: "Crusader Helmet", type: "Helmet", tier: 8 },
  { name: "Warlord Helmet", type: "Helmet", tier: 8 },
  { name: "Berserker Helmet", type: "Helmet", tier: 9 },
  { name: "Centurion Helmet", type: "Helmet", tier: 9 },
  { name: "Juggernaut Furnace", type: "Helmet", tier: 10 },
  { name: "Gobble Lord Helm", type: "Helmet", tier: 10 },
  { name: "Opulent Heaume", type: "Helmet", tier: 10 },
  { name: "Celesteel Heaume", type: "Helmet", tier: 11 },
  { name: "Canid Helmet", type: "Helmet", tier: 11 },
  { name: "Cupid's Heaume", type: "Helmet", tier: 11 },
  { name: "Vermilion Guard Helm", type: "Helmet", tier: 12 },
  { name: "Onyx King Helm", type: "Helmet", tier: 12 },
  { name: "Thorn Baron Helm", type: "Helmet", tier: 12 },
  { name: "Balefire Gaze", type: "Helmet", tier: 13 },
  { name: "Taishōgun Kabuto", type: "Helmet", tier: 13 },
  { name: "Leather Cap", type: "Rogue Hat", tier: 1 },
  { name: "Canopy Cap", type: "Rogue Hat", tier: 1 },
  { name: "Brimmed Hat", type: "Rogue Hat", tier: 2 },
  { name: "Feathered Hat", type: "Rogue Hat", tier: 3 },
  { name: "Tricorn", type: "Rogue Hat", tier: 4 },
  { name: "Silk Hood", type: "Rogue Hat", tier: 5 },
  { name: "Santa's Elf Hat", type: "Rogue Hat", tier: 5 },
  { name: "Pharaoh's Nemes", type: "Rogue Hat", tier: 5 },
  { name: "Pirate Hat", type: "Rogue Hat", tier: 6 },
  { name: "Lovely Hat", type: "Rogue Hat", tier: 6 },
  { name: "Night Cowl", type: "Rogue Hat", tier: 7 },
  { name: "Nomad Veil", type: "Rogue Hat", tier: 7 },
  { name: "Harvester's Hood", type: "Rogue Hat", tier: 7 },
  { name: "Windrunner Hat", type: "Rogue Hat", tier: 8 },
  { name: "Blue Spirit Mask", type: "Rogue Hat", tier: 8 },
  { name: "Musketeer Hat", type: "Rogue Hat", tier: 8 },
  { name: "Drakeskin Mask", type: "Rogue Hat", tier: 9 },
  { name: "Storm Dragon Mask", type: "Rogue Hat", tier: 9 },
  { name: "Grand Tyrolean", type: "Rogue Hat", tier: 9 },
  { name: "Corsair Tricorn", type: "Rogue Hat", tier: 10 },
  { name: "Republic Coiffe", type: "Rogue Hat", tier: 10 },
  { name: "Everdusk Cowl", type: "Rogue Hat", tier: 11 },
  { name: "Abyssal Hood", type: "Rogue Hat", tier: 11 },
  { name: "Rogue Sombrero", type: "Rogue Hat", tier: 11 },
  { name: "Cat Burglar Hood", type: "Rogue Hat", tier: 11 },
  { name: "Opulent Sallet", type: "Rogue Hat", tier: 11 },
  { name: "Dawn Thief Cowl", type: "Rogue Hat", tier: 12 },
  { name: "Bunbun Masquerade", type: "Rogue Hat", tier: 12 },
  { name: "Dragonseeker Goggles", type: "Rogue Hat", tier: 12 },
  { name: "Kitsune Spirit Mask", type: "Rogue Hat", tier: 12 },
  { name: "Wildhunt Skull", type: "Rogue Hat", tier: 13 },
  { name: "Stitched Cone", type: "Magician Hat", tier: 1 },
  { name: "Black Cowl", type: "Magician Hat", tier: 2 },
  { name: "Druid Laurels", type: "Magician Hat", tier: 3 },
  { name: "Apprentice Tiara", type: "Magician Hat", tier: 3 },
  { name: "Bronze Circlet", type: "Magician Hat", tier: 4 },
  { name: "Wizard Hat", type: "Magician Hat", tier: 5 },
  { name: "Hat of the Four Winds", type: "Magician Hat", tier: 5 },
  { name: "Ostara Hat", type: "Magician Hat", tier: 5 },
  { name: "Witch Hat", type: "Magician Hat", tier: 6 },
  { name: "Waterproof Lilycap", type: "Magician Hat", tier: 6 },
  { name: "Owl Cowl", type: "Magician Hat", tier: 6 },
  { name: "Tactician Hat", type: "Magician Hat", tier: 7 },
  { name: "Summoner Hat", type: "Magician Hat", tier: 7 },
  { name: "Ivory Queen Crown", type: "Magician Hat", tier: 7 },
  { name: "Shaman Hat", type: "Magician Hat", tier: 8 },
  { name: "Luxurious Headdress", type: "Magician Hat", tier: 8 },
  { name: "Astral Hat", type: "Magician Hat", tier: 9 },
  { name: "Raven Mask", type: "Magician Hat", tier: 9 },
  { name: "Spellward Hat", type: "Magician Hat", tier: 9 },
  { name: "Opal Diadem", type: "Magician Hat", tier: 10 },
  { name: "Night Crown", type: "Magician Hat", tier: 10 },
  { name: "Djinn Veil", type: "Magician Hat", tier: 11 },
  { name: "Elegant Top Hat", type: "Magician Hat", tier: 11 },
  { name: "Ice Queen's Summer Hat", type: "Magician Hat", tier: 11 },
  { name: "Exarch Mitre", type: "Magician Hat", tier: 12 },
  { name: "Sakura Eboshi", type: "Magician Hat", tier: 12 },
  { name: "Opulent Headdress", type: "Magician Hat", tier: 12 },
  { name: "Phoenix Crest", type: "Magician Hat", tier: 12 },
  { name: "Empress Hairpins", type: "Magician Hat", tier: 12 },
  { name: "Voidminster Hat", type: "Magician Hat", tier: 13 },
  { name: "Elysium Halo", type: "Magician Hat", tier: 13 },
  { name: "Iron Armguards", type: "Gauntlets", tier: 1 },
  { name: "Plated Gauntlets", type: "Gauntlets", tier: 2 },
  { name: "Warrior Gauntlets", type: "Gauntlets", tier: 3 },
  { name: "Demi Gauntlets", type: "Gauntlets", tier: 4 },
  { name: "Pumpkin Gauntlets", type: "Gauntlets", tier: 4 },
  { name: "Knight Gauntlets", type: "Gauntlets", tier: 5 },
  { name: "Santa's Guard Gauntlets", type: "Gauntlets", tier: 5 },
  { name: "Hands of the Fifth", type: "Gauntlets", tier: 5 },
  { name: "Paladin Gauntlets", type: "Gauntlets", tier: 6 },
  { name: "Sungrasp Gauntlets", type: "Gauntlets", tier: 6 },
  { name: "Landsknecht Gauntlets", type: "Gauntlets", tier: 6 },
  { name: "Samurai Kote", type: "Gauntlets", tier: 7 },
  { name: "Republic Gauntlets", type: "Gauntlets", tier: 7 },
  { name: "Fruity Gauntlets", type: "Gauntlets", tier: 7 },
  { name: "General Gauntlets", type: "Gauntlets", tier: 8 },
  { name: "Berserker Gauntlets", type: "Gauntlets", tier: 9 },
  { name: "Luxurious Gauntlets", type: "Gauntlets", tier: 9 },
  { name: "Juggernaut Grip", type: "Gauntlets", tier: 10 },
  { name: "Winter's Touch", type: "Gauntlets", tier: 10 },
  { name: "Celesteel Gauntlets", type: "Gauntlets", tier: 11 },
  { name: "Gaia's Hold", type: "Gauntlets", tier: 11 },
  { name: "Vanguard Gauntlets", type: "Gauntlets", tier: 11 },
  { name: "Huscarl Gauntlets", type: "Gauntlets", tier: 11 },
  { name: "Vermilion Guard Might", type: "Gauntlets", tier: 12 },
  { name: "Goon's Facesmackers", type: "Gauntlets", tier: 12 },
  { name: "Opulent Dracofists", type: "Gauntlets", tier: 12 },
  { name: "Tyrant Fists", type: "Gauntlets", tier: 12 },
  { name: "Balefire Gauntlets", type: "Gauntlets", tier: 13 },
  { name: "Power Gauntlet", type: "Gauntlets", tier: 13 },
  { name: "Leather Gloves", type: "Gloves", tier: 1 },
  { name: "Bracers", type: "Gloves", tier: 2 },
  { name: "Thief's Gloves", type: "Gloves", tier: 3 },
  { name: "Swift Mitts", type: "Gloves", tier: 3 },
  { name: "Patchleather Bracers", type: "Gloves", tier: 3 },
  { name: "Studded Gloves", type: "Gloves", tier: 4 },
  { name: "Regal Bangles", type: "Gloves", tier: 4 },
  { name: "Elven Vambraces", type: "Gloves", tier: 5 },
  { name: "Ostara Gloves", type: "Gloves", tier: 5 },
  { name: "Savage Claws", type: "Gloves", tier: 6 },
  { name: "Black Wyrm Claws", type: "Gloves", tier: 6 },
  { name: "Ninja Gloves", type: "Gloves", tier: 7 },
  { name: "Cat Burglar Claws", type: "Gloves", tier: 7 },
  { name: "Windrunner Gloves", type: "Gloves", tier: 8 },
  { name: "Sakura Cuffs", type: "Gloves", tier: 8 },
  { name: "Drakeskin Gloves", type: "Gloves", tier: 9 },
  { name: "Mountain Man Mitts", type: "Gloves", tier: 9 },
  { name: "Corsair Gloves", type: "Gloves", tier: 10 },
  { name: "Fortunate Gloves", type: "Gloves", tier: 10 },
  { name: "Opulent Grasp", type: "Gloves", tier: 10 },
  { name: "Everdusk Gloves", type: "Gloves", tier: 11 },
  { name: "Raptor Wings", type: "Gloves", tier: 11 },
  { name: "Nightwing Vambraces", type: "Gloves", tier: 11 },
  { name: "Dawn Thief's Touch", type: "Gloves", tier: 12 },
  { name: "Swindler's Fingers", type: "Gloves", tier: 12 },
  { name: "Gloves of Rhythm", type: "Gloves", tier: 12 },
  { name: "Gants d'Artagnan", type: "Gloves", tier: 12 },
  { name: "Wildhunt Gloves", type: "Gloves", tier: 13 },
  { name: "Shin Guards", type: "Heavy Footwear", tier: 1 },
  { name: "Long Boots", type: "Heavy Footwear", tier: 2 },
  { name: "Iron Greaves", type: "Heavy Footwear", tier: 3 },
  { name: "Hero's Boots", type: "Heavy Footwear", tier: 3 },
  { name: "Reinforced Greaves", type: "Heavy Footwear", tier: 4 },
  { name: "Plated Squeakers", type: "Heavy Footwear", tier: 4 },
  { name: "Knight Sollerets", type: "Heavy Footwear", tier: 5 },
  { name: "Cindersole", type: "Heavy Footwear", tier: 5 },
  { name: "Warlord Boots", type: "Heavy Footwear", tier: 5 },
  { name: "Paladin Boots", type: "Heavy Footwear", tier: 6 },
  { name: "Canid Paws", type: "Heavy Footwear", tier: 6 },
  { name: "Samurai Haidate", type: "Heavy Footwear", tier: 7 },
  { name: "Topaz Greaves", type: "Heavy Footwear", tier: 7 },
  { name: "General Greaves", type: "Heavy Footwear", tier: 8 },
  { name: "Berserker Stompers", type: "Heavy Footwear", tier: 9 },
  { name: "Luxurious Boots", type: "Heavy Footwear", tier: 9 },
  { name: "Vanguard Greaves", type: "Heavy Footwear", tier: 9 },
  { name: "Juggernaut Greaves", type: "Heavy Footwear", tier: 10 },
  { name: "Bunbun Booties", type: "Heavy Footwear", tier: 10 },
  { name: "Greaves of the Fifth", type: "Heavy Footwear", tier: 10 },
  { name: "Celesteel Boots", type: "Heavy Footwear", tier: 11 },
  { name: "Star-Spangled Greaves", type: "Heavy Footwear", tier: 11 },
  { name: "Santa's Guard Boots", type: "Heavy Footwear", tier: 11 },
  { name: "Vermilion Guard Greaves", type: "Heavy Footwear", tier: 12 },
  { name: "Boots of Zeal", type: "Heavy Footwear", tier: 12 },
  { name: "Fruity Booties", type: "Heavy Footwear", tier: 12 },
  { name: "Opulent Greaves", type: "Heavy Footwear", tier: 12 },
  { name: "Rex Stompers", type: "Heavy Footwear", tier: 12 },
  { name: "Balefire Greaves", type: "Heavy Footwear", tier: 13 },
  { name: "Leather Boots", type: "Light Footwear", tier: 1 },
  { name: "Trailblazers", type: "Light Footwear", tier: 1 },
  { name: "Flip-Flops", type: "Light Footwear", tier: 2 },
  { name: "Soft Shoes", type: "Light Footwear", tier: 3 },
  { name: "Legionnaire Sandals", type: "Light Footwear", tier: 3 },
  { name: "Thief's Shoes", type: "Light Footwear", tier: 4 },
  { name: "Perennial Sandals", type: "Light Footwear", tier: 4 },
  { name: "Elven Shoes", type: "Light Footwear", tier: 5 },
  { name: "Moonlight Zōri", type: "Light Footwear", tier: 5 },
  { name: "Savage Stride", type: "Light Footwear", tier: 6 },
  { name: "Sakura Tabi", type: "Light Footwear", tier: 6 },
  { name: "Sultan Steps", type: "Light Footwear", tier: 6 },
  { name: "Ninja Tabi", type: "Light Footwear", tier: 7 },
  { name: "Nightwing Shoes", type: "Light Footwear", tier: 7 },
  { name: "Windrunner Boots", type: "Light Footwear", tier: 8 },
  { name: "Alpine Stride", type: "Light Footwear", tier: 8 },
  { name: "Drakeskin Boots", type: "Light Footwear", tier: 9 },
  { name: "Plaguewalkers", type: "Light Footwear", tier: 9 },
  { name: "Shoes of Style", type: "Light Footwear", tier: 9 },
  { name: "Corsair Boots", type: "Light Footwear", tier: 10 },
  { name: "Cloudwalker Steps", type: "Light Footwear", tier: 10 },
  { name: "Everdusk Boots", type: "Light Footwear", tier: 11 },
  { name: "Raptor Talons", type: "Light Footwear", tier: 11 },
  { name: "Opulent Footwraps", type: "Light Footwear", tier: 11 },
  { name: "Dawn Thief's Path", type: "Light Footwear", tier: 12 },
  { name: "Desperado Spurs", type: "Light Footwear", tier: 12 },
  { name: "Hunter Moccasins", type: "Light Footwear", tier: 12 },
  { name: "Fairy Sandals", type: "Light Footwear", tier: 12 },
  { name: "Wildhunt Sandals", type: "Light Footwear", tier: 13 },
  { name: "Wooden Shield", type: "Shield", tier: 1 },
  { name: "Heavy Buckler", type: "Shield", tier: 2 },
  { name: "Oaken Shield", type: "Shield", tier: 3 },
  { name: "Iron Shield", type: "Shield", tier: 4 },
  { name: "Aurum Ward", type: "Shield", tier: 4 },
  { name: "Teardrop Shield", type: "Shield", tier: 5 },
  { name: "Imperial Scutum", type: "Shield", tier: 5 },
  { name: "Champion Vigil", type: "Shield", tier: 5 },
  { name: "Mythril Aspis", type: "Shield", tier: 6 },
  { name: "Raider Buckler", type: "Shield", tier: 6 },
  { name: "Gaia Aegis", type: "Shield", tier: 6 },
  { name: "Wyrmguard", type: "Shield", tier: 7 },
  { name: "Vanguard Buckler", type: "Shield", tier: 7 },
  { name: "Ancestor Totem", type: "Shield", tier: 8 },
  { name: "Angelic Pavise", type: "Shield", tier: 9 },
  { name: "Prometheon", type: "Shield", tier: 9 },
  { name: "Milesian Shield", type: "Shield", tier: 9 },
  { name: "Bunbun Buckler", type: "Shield", tier: 9 },
  { name: "Luxurious Aegis", type: "Shield", tier: 9 },
  { name: "Goldmane Guard", type: "Shield", tier: 10 },
  { name: "Emperor Wyrmguard", type: "Shield", tier: 10 },
  { name: "Bearded Paragon", type: "Shield", tier: 11 },
  { name: "Honeycomb Defender", type: "Shield", tier: 11 },
  { name: "Crystalice Targe", type: "Shield", tier: 11 },
  { name: "Abyssal Artifact", type: "Shield", tier: 12 },
  { name: "Titan Shield", type: "Shield", tier: 12 },
  { name: "Opulent Buckler", type: "Shield", tier: 12 },
  { name: "Bastion of Dawn", type: "Shield", tier: 12 },
  { name: "Elongo Shield", type: "Shield", tier: 12 },
  { name: "Chloroshield", type: "Shield", tier: 13 },
  { name: "Mundra's Aegis", type: "Shield", tier: 13 },
  { name: "Adventurer Cape", type: "Cloak", tier: 3 },
  { name: "Administrator Cloak", type: "Cloak", tier: 4 },
  { name: "Druid Cloak", type: "Cloak", tier: 5 },
  { name: "Imperial Cape", type: "Cloak", tier: 6 },
  { name: "Vampire Wings", type: "Cloak", tier: 6 },
  { name: "Elven Cloak", type: "Cloak", tier: 7 },
  { name: "Beast King's Cloak", type: "Cloak", tier: 8 },
  { name: "Dragonlord Crest", type: "Cloak", tier: 9 },
  { name: "Tyrant Cloak", type: "Cloak", tier: 9 },
  { name: "Archbishop Mantle", type: "Cloak", tier: 10 },
  { name: "Voidcloth From Beyond", type: "Cloak", tier: 11 },
  { name: "Opulent Cloak", type: "Cloak", tier: 11 },
  { name: "Woven Lilycloak", type: "Cloak", tier: 11 },
  { name: "Herald's Mantle", type: "Cloak", tier: 12 },
  { name: "Sakura Cloak", type: "Cloak", tier: 12 },
  { name: "Fairy Wings", type: "Cloak", tier: 12 },
  { name: "Cloak Everflowing", type: "Cloak", tier: 13 },
  { name: "Iron Ring", type: "Ring", tier: 1 },
  { name: "Alloy Loop", type: "Ring", tier: 2 },
  { name: "Ruby Ring", type: "Ring", tier: 3 },
  { name: "Emerald Ring", type: "Ring", tier: 3 },
  { name: "Silver Band", type: "Ring", tier: 4 },
  { name: "Ring of Passion", type: "Ring", tier: 4 },
  { name: "Noble Ring", type: "Ring", tier: 5 },
  { name: "Ring of Rhythm", type: "Ring", tier: 5 },
  { name: "Claud's Will", type: "Ring", tier: 5 },
  { name: "Knight Signet", type: "Ring", tier: 6 },
  { name: "Ring of Liberty", type: "Ring", tier: 6 },
  { name: "Qian Loop", type: "Ring", tier: 6 },
  { name: "Batrachite Stone", type: "Ring", tier: 7 },
  { name: "Soulstone Ring", type: "Ring", tier: 7 },
  { name: "Ring of the Chosen", type: "Ring", tier: 7 },
  { name: "Brimstone Coil", type: "Ring", tier: 8 },
  { name: "Ring of Vampire Kin", type: "Ring", tier: 8 },
  { name: "Fairfolk Band", type: "Ring", tier: 9 },
  { name: "Dawnflower Ring", type: "Ring", tier: 9 },
  { name: "Valedictorian Ring", type: "Ring", tier: 9 },
  { name: "Luxurious Signet", type: "Ring", tier: 9 },
  { name: "Borealis", type: "Ring", tier: 10 },
  { name: "Northwind Gem", type: "Ring", tier: 10 },
  { name: "Blizzard Ring", type: "Ring", tier: 10 },
  { name: "Bunbun Band", type: "Ring", tier: 10 },
  { name: "Rubicon Prison", type: "Ring", tier: 11 },
  { name: "Crunchy Bracelet", type: "Ring", tier: 11 },
  { name: "Ring of New Beginnings", type: "Ring", tier: 11 },
  { name: "Pearlescent Perfection", type: "Ring", tier: 12 },
  { name: "Crystalice Loop", type: "Ring", tier: 12 },
  { name: "Ogun's Onyx Ring", type: "Ring", tier: 12 },
  { name: "Maple Ration Mini", type: "Ring", tier: 12 },
  { name: "Opulent Signet", type: "Ring", tier: 12 },
  { name: "Mark of Ouroboros", type: "Ring", tier: 13 },
  { name: "Memento", type: "Amulet", tier: 1 },
  { name: "Jade Pendant", type: "Amulet", tier: 2 },
  { name: "Iron Bond", type: "Amulet", tier: 3 },
  { name: "Mundra's Amulet", type: "Amulet", tier: 3 },
  { name: "Sun Pendant", type: "Amulet", tier: 4 },
  { name: "Eclipse Amulet", type: "Amulet", tier: 4 },
  { name: "Medal of Honor", type: "Amulet", tier: 4 },
  { name: "Noble Chain", type: "Amulet", tier: 5 },
  { name: "Lucky Medallion", type: "Amulet", tier: 5 },
  { name: "Luxurious Charm", type: "Amulet", tier: 5 },
  { name: "Holy Symbol", type: "Amulet", tier: 6 },
  { name: "Convenient Pendant", type: "Amulet", tier: 6 },
  { name: "Trinket of the Fifth", type: "Amulet", tier: 6 },
  { name: "Titanium Torc", type: "Amulet", tier: 7 },
  { name: "Magical Timepiece", type: "Amulet", tier: 7 },
  { name: "Magatama Necklace", type: "Amulet", tier: 8 },
  { name: "Dragonsoul Pendant", type: "Amulet", tier: 8 },
  { name: "Archivist Glasses", type: "Amulet", tier: 8 },
  { name: "Stygian Phylactery", type: "Amulet", tier: 9 },
  { name: "Ursa Totem", type: "Amulet", tier: 9 },
  { name: "P.E.T. Portable", type: "Amulet", tier: 9 },
  { name: "Alimyriad", type: "Amulet", tier: 10 },
  { name: "Freyja's Talisman", type: "Amulet", tier: 10 },
  { name: "VIP Talisman", type: "Amulet", tier: 10 },
  { name: "Brísingamen", type: "Amulet", tier: 11 },
  { name: "Monsoon Heart", type: "Amulet", tier: 11 },
  { name: "Forlorn Acorn", type: "Amulet", tier: 11 },
  { name: "Gyatso's Amulet", type: "Amulet", tier: 11 },
  { name: "Fellgrove Talisman", type: "Amulet", tier: 11 },
  { name: "Titania's Keepsake", type: "Amulet", tier: 12 },
  { name: "Opulent Carcanet", type: "Amulet", tier: 12 },
  { name: "Gamepad Mini", type: "Amulet", tier: 12 },
  { name: "Eternal Hourglass", type: "Amulet", tier: 12 },
  { name: "Fairy Wreath", type: "Amulet", tier: 12 },
  { name: "Titania's Timepiece", type: "Amulet", tier: 13 },
  { name: "Troublin", type: "Familiar", tier: 3 },
  { name: "Yeti", type: "Familiar", tier: 4 },
  { name: "Toadwitch", type: "Familiar", tier: 5 },
  { name: "Mushgoon", type: "Familiar", tier: 6 },
  { name: "Anubis", type: "Familiar", tier: 7 },
  { name: "Cyclops", type: "Familiar", tier: 8 },
  { name: "Tyrant", type: "Familiar", tier: 9 },
  { name: "Mermaid", type: "Familiar", tier: 10 },
  { name: "Harpy", type: "Familiar", tier: 11 },
  { name: "Opulent Golem", type: "Familiar", tier: 11 },
  { name: "Crushtacean", type: "Familiar", tier: 12 },
  { name: "Voidling", type: "Familiar", tier: 13 },
  { name: "Bacon and Eggs", type: "Meal", tier: 3 },
  { name: "Gua Bao", type: "Meal", tier: 4 },
  { name: "CosmOs Cereals", type: "Meal", tier: 4 },
  { name: "Poutine", type: "Meal", tier: 5 },
  { name: "Sugar Shack Special", type: "Meal", tier: 5 },
  { name: "Cheeseburger", type: "Meal", tier: 6 },
  { name: "Margherita Pizza", type: "Meal", tier: 6 },
  { name: "Power-Up Pie", type: "Meal", tier: 6 },
  { name: "Ahi Poke Bowl", type: "Meal", tier: 7 },
  { name: "Creamy Scallops", type: "Meal", tier: 7 },
  { name: "Sushi", type: "Meal", tier: 8 },
  { name: "Super Spicy Curry", type: "Meal", tier: 9 },
  { name: "Veggie Kebabs", type: "Meal", tier: 10 },
  { name: "Deluxe Ramen", type: "Meal", tier: 11 },
  { name: "Steamed Sea Bass", type: "Meal", tier: 11 },
  { name: "Huli-Huli Chicken", type: "Meal", tier: 12 },
  { name: "Opulent Tamales", type: "Meal", tier: 12 },
  { name: "Pot of Paella", type: "Meal", tier: 13 },
  { name: "Cookie Plate", type: "Dessert", tier: 3 },
  { name: "Shaved Ice", type: "Dessert", tier: 4 },
  { name: "Taiyaki", type: "Dessert", tier: 5 },
  { name: "Cheesecake", type: "Dessert", tier: 6 },
  { name: "Chocolate Box", type: "Dessert", tier: 6 },
  { name: "Macaron Set", type: "Dessert", tier: 7 },
  { name: "Strawberry Mochi", type: "Dessert", tier: 8 },
  { name: "Matcha Swiss Roll", type: "Dessert", tier: 9 },
  { name: "Pineapple Cake", type: "Dessert", tier: 10 },
  { name: "Tuxedo Cake", type: "Dessert", tier: 11 },
  { name: "Halo-Halo", type: "Dessert", tier: 12 },
  { name: "Coconut Cream Cake", type: "Dessert", tier: 12 },
  { name: "Opulent Churros", type: "Dessert", tier: 12 },
  { name: "Glazed Mirror Cake", type: "Dessert", tier: 12 },
  { name: "Ultimate Fruit Salad", type: "Dessert", tier: 13 },
  { name: "Chipped Runestone", type: "Runestone", tier: 4 },
  { name: "Flawed Runestone", type: "Runestone", tier: 7 },
  { name: "Chiseled Runestone", type: "Runestone", tier: 9 },
  { name: "Perfect Runestone", type: "Runestone", tier: 12 },
  { name: "Lesser Moonstone", type: "Moonstone", tier: 4 },
  { name: "Superior Moonstone", type: "Moonstone", tier: 7 },
  { name: "Greater Moonstone", type: "Moonstone", tier: 10 },
  { name: "Perfect Moonstone", type: "Moonstone", tier: 12 },
  { name: "Ember Element", type: "Enchantment", tier: 4 },
  { name: "Flame Element", type: "Enchantment", tier: 7 },
  { name: "Blaze Element", type: "Enchantment", tier: 9 },
  { name: "Inferno Element", type: "Enchantment", tier: 12 },
  { name: "Bubble Element", type: "Enchantment", tier: 4 },
  { name: "Tide Element", type: "Enchantment", tier: 7 },
  { name: "Flood Element", type: "Enchantment", tier: 9 },
  { name: "Torrent Element", type: "Enchantment", tier: 12 },
  { name: "Breeze Element", type: "Enchantment", tier: 4 },
  { name: "Gale Element", type: "Enchantment", tier: 7 },
  { name: "Tempest Element", type: "Enchantment", tier: 9 },
  { name: "Hurricane Element", type: "Enchantment", tier: 12 },
  { name: "Nature Element", type: "Enchantment", tier: 4 },
  { name: "Wild Element", type: "Enchantment", tier: 7 },
  { name: "Primal Element", type: "Enchantment", tier: 9 },
  { name: "Primeval Element", type: "Enchantment", tier: 12 },
  { name: "Light Element", type: "Enchantment", tier: 4 },
  { name: "Holy Element", type: "Enchantment", tier: 7 },
  { name: "Sacred Element", type: "Enchantment", tier: 9 },
  { name: "Divine Element", type: "Enchantment", tier: 12 },
  { name: "Corrupted Element", type: "Enchantment", tier: 4 },
  { name: "Unholy Element", type: "Enchantment", tier: 7 },
  { name: "Nightmare Element", type: "Enchantment", tier: 9 },
  { name: "Abyssal Element", type: "Enchantment", tier: 12 },
  { name: "Luxurious Element", type: "Enchantment", tier: 5 },
  { name: "Opulent Element", type: "Enchantment", tier: 10 },
  { name: "Ram Spirit", type: "Enchantment", tier: 4 },
  { name: "Wolf Spirit", type: "Enchantment", tier: 4 },
  { name: "Ox Spirit", type: "Enchantment", tier: 4 },
  { name: "Eagle Spirit", type: "Enchantment", tier: 4 },
  { name: "Viper Spirit", type: "Enchantment", tier: 4 },
  { name: "Cat Spirit", type: "Enchantment", tier: 4 },
  { name: "Bunny Spirit", type: "Enchantment", tier: 4 },
  { name: "Xolotl Spirit", type: "Enchantment", tier: 5 },
  { name: "Rhino Spirit", type: "Enchantment", tier: 7 },
  { name: "Owl Spirit", type: "Enchantment", tier: 7 },
  { name: "Armadillo Spirit", type: "Enchantment", tier: 7 },
  { name: "Lizard Spirit", type: "Enchantment", tier: 7 },
  { name: "Horse Spirit", type: "Enchantment", tier: 7 },
  { name: "Hippo Spirit", type: "Enchantment", tier: 7 },
  { name: "Shark Spirit", type: "Enchantment", tier: 9 },
  { name: "Walrus Spirit", type: "Enchantment", tier: 9 },
  { name: "Lion Spirit", type: "Enchantment", tier: 9 },
  { name: "Bear Spirit", type: "Enchantment", tier: 9 },
  { name: "Mammoth Spirit", type: "Enchantment", tier: 9 },
  { name: "Dinosaur Spirit", type: "Enchantment", tier: 9 },
  { name: "Tiger Spirit", type: "Enchantment", tier: 9 },
  { name: "Quetzalcoatl Spirit", type: "Enchantment", tier: 10 },
  { name: "Phoenix Spirit", type: "Enchantment", tier: 12 },
  { name: "Hydra Spirit", type: "Enchantment", tier: 12 },
  { name: "Tarrasque Spirit", type: "Enchantment", tier: 12 },
  { name: "Carbuncle Spirit", type: "Enchantment", tier: 12 },
  { name: "Chimera Spirit", type: "Enchantment", tier: 12 },
  { name: "Kraken Spirit", type: "Enchantment", tier: 12 },
  { name: "Christmas Spirit", type: "Enchantment", tier: 12 },
]);
